---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords: whats new, enhancements, new features 
summary: NetApp actualiza regularmente la API REST de Astra Control para ofrecerle nuevas funciones, mejoras y correcciones de errores. 
---
= Novedades de la API ASTRA Control REST
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp actualiza regularmente la API REST de Astra Control para ofrecerle nuevas funciones, mejoras y correcciones de errores.



== 14 de marzo de 2024 (24,02)

Tanto Astra Control Service como Astra Control Center se han actualizado con la versión 24,02.



=== Correcciones de errores menores

La versión 24,02 se centra principalmente en solucionar una serie de errores menores. No se han añadido nuevos tipos de recursos a la API de Astra Control.



=== Vista previa tecnológica: Flujos de trabajo declarativos de Kubernetes

Astra Control Center 24,02 incluye una funcionalidad de Kubernetes declarativa que le permite realizar tareas de gestión de datos desde un recurso personalizado de Kubernetes nativo (CR). Esta función aún no está disponible en general. Consulte https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html["Astra Control Center: Lo nuevo"^] para obtener más información si es necesario.



== 7 de noviembre de 2023 (23,10)

Tanto Astra Control Service como Astra Control Center se han actualizado con la versión 23,10. Existen mejoras selectivas en la API de REST para admitir las nuevas funciones.



=== Back-ends de almacenamiento ampliado

Es posible habilitar las operaciones de backup y restauración para `ontap-nas-economy` back-ends de almacenamiento.



=== Backups inmutables

Astra Control ahora admite backups de solo lectura inalterables como capa de seguridad adicional frente al malware y otras amenazas.



=== Control mejorado de los ganchos de ejecución

A partir de esta versión, la funcionalidad de los ganchos de ejecución se puede activar o desactivar para mayor seguridad (está desactivada de forma predeterminada). Si aún no has creado ganchos de ejecución para usarlos con Astra Control, debes habilitar la función de ganchos de ejecución para comenzar a crear ganchos. Si ha creado enlaces de ejecución antes de esta versión, la funcionalidad de enlaces de ejecución permanece activada y puede utilizar los enlaces como lo haría normalmente.



== 27 de julio de 2023 (23,07)

Esta versión incluye mejoras selectivas en la API de REST. Tanto Astra Control Service como Astra Control Center se han actualizado con la versión 23,07.



=== Operaciones de clonado y replicación

La operación de clonado ahora solo admite clones activos (el estado actual de la aplicación gestionada). Para clonar desde una snapshot o un backup, debe usar la operación de restauración. Además, ahora las aplicaciones se pueden replicar entre back-ends de almacenamiento de ONTAP dentro del mismo clúster de Kubernetes.



=== Back-ends de almacenamiento ampliado

Ahora se pueden utilizar back-ends de almacenamiento adicionales con Astra Control Center, entre los que se incluyen:

* NetApp MetroCluster en una configuración con ampliación
* https://longhorn.io/["El Longhorn"^] 1.5.0 y posterior




=== Nuevo tipo de enlace de ejecución

El nuevo tipo de gancho de ejecución *post-failover* está disponible con Astra Control Center.



== 27 de junio de 2023 (23,06)

Esta versión incluye actualizaciones selectivas de la API de REST.



=== Azure Marketplace

Las suscripciones de Azure Marketplace ahora se facturan por hora en lugar de por minuto. Consulte también https://docs.netapp.com/us-en/astra-control-service/use/set-up-billing.html["Configurar facturación"^].



=== Optimización de Restic

Puede activar la optimización del rendimiento para los backups de resincronización mediante la marca `useResticParallel` en el nuevo `astra.datamover` Recurso de la API de configuración. Cuando se establece en `true`, el número de `backendConnections` Esos usos ráticos aumentan cuando se realizan backups de grandes volúmenes en un contenedor de Azure. Para volúmenes de 1TB a 4TB, se utilizan conexiones 128. En el caso de los volúmenes de más de 4TB GB, se utilizan 512 conexiones back-end.



== 30 de mayo de 2023 (23,05)

Esta versión incluye actualizaciones selectivas de la API de REST.



=== Operaciones de restauración selectivas

Puede seleccionar la clase de almacenamiento de destino durante las operaciones de restauración o clonado.



=== Habilite ANF Pools dinámicos para clústeres autogestionados

Al realizar un backup de una aplicación gestionada en un clúster privado de las instalaciones que tiene un back-end de almacenamiento ANF, ahora puede habilitar la función dinámica ANF Pools mediante un ID de suscripción. Consulte link:../workflows_infra/wf_enable_anf_dyn_pools.html["Habilitar pools de ANF dinámicos"] si quiere más información.



== 25 de abril de 2023 (23,04)

Esta versión incluye actualizaciones selectivas de la API de REST.



=== Operaciones de restauración selectivas

Puede incluir o excluir de forma selectiva los recursos de la aplicación durante las operaciones de restauración. Esto se realiza mediante una regla de filtro basada en un espacio de nombres, nombre, etiqueta o valor de GroupVersionKind específico.



=== Soporte para aplicaciones de solo datos

El soporte para la gestión de aplicaciones se ha extendido a aplicaciones de solo datos.



== 17 de enero de 2023 (23.01)

Esta versión incluye una actualización secundaria de la API DE REST.



=== Funciones mejoradas de enlaces de ejecución con filtros

Cuando utilice ganchos de ejecución, ahora puede agregar filtros para controlar a qué contenedores coincidirán un gancho. Si crea varios filtros para un único enlace de ejecución, se combinan con un operador y lógico. Puede definir hasta 10 filtros activos por enlace de ejecución.



== 22 de noviembre de 2022 (22.11)

Esta versión incluye una ampliación y actualización de la API DE REST, así como compatibilidad con espacio de nombres y LDAP mejoradas.



=== Recursos de Astra nuevos y mejorados

Se han añadido cuatro nuevos tipos de recursos: *ApiResource*, *ldapGroup*, *LDAPUser* y *Task*. Además, se han mejorado varios recursos y puntos finales existentes.



=== Supervisión de soporte para tareas de larga duración

Los nuevos extremos de tareas proporcionan acceso a los recursos de tareas gestionados y se pueden utilizar para mostrar el estado de las tareas internas de ejecución prolongada.



=== Mejores situaciones de uso de espacios de nombres

Se ha agregado compatibilidad con aplicaciones que abarcan varios espacios de nombres, así como recursos de clúster asociados con recursos que permiten un espacio de nombres adecuado.



=== Más suscripciones al cloud

Ahora se pueden añadir varias suscripciones a cuentas para cada uno de los proveedores de cloud.



=== Flujos de trabajo adicionales

Se han agregado flujos de trabajo adicionales que ilustran la API DE REST de Astra Control. Consulte link:../workflows_infra/workflows_infra_before.html["Flujos de trabajo de infraestructura"] y.. link:../workflows/workflows_before.html["Flujos de trabajo de gestión"] si quiere más información.

.Información relacionada
* https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html["Astra Control Center: Lo nuevo"^]




== 10 de agosto de 2022 (22.08)

Esta versión incluye una ampliación y actualización de la API DE REST, así como funciones de seguridad y administración mejoradas.



=== Recursos de Astra nuevos y mejorados

Se han añadido tres nuevos tipos de recursos: *Certificado*, *Grupo* y *AppMirror*. Además, se han actualizado las versiones de varios recursos existentes.



=== Autenticación LDAP

Opcionalmente, puede configurar Astra Control Center para que se integre con un servidor LDAP para autenticar a los usuarios Astra seleccionados. Consulte link:../workflows_infra/ldap_prepare.html["Configuración de LDAP"] si quiere más información.



=== Gancho de ejecución mejorado

Se ha añadido soporte para los ganchos de ejecución con la versión Astra Control 21.12. Además de los enlaces de ejecución previa y posterior a la instantánea existentes, ahora puede configurar los siguientes tipos de enlaces de ejecución con la versión 22.08:

* Previo al backup
* Después del backup
* Después de la restauración


Astra Control ahora también permite utilizar la misma secuencia de comandos para múltiples enlaces de ejecución.



=== Replicación de aplicaciones mediante SnapMirror

Ahora puede replicar cambios de datos y aplicaciones entre clústeres mediante la tecnología SnapMirror de NetApp. Esta mejora puede utilizarse para mejorar sus funcionalidades de continuidad del negocio y recuperación.

.Información relacionada
* https://docs.netapp.com/us-en/astra-control-center-2208/release-notes/whats-new.html["Astra Control Center 22.08: Novedades"^]




== 26 de abril de 2022 (22.04)

Esta versión incluye una ampliación y actualización de la API DE REST, así como funciones de seguridad y administración mejoradas.



=== Recursos de Astra nuevos y mejorados

Se han añadido dos nuevos tipos de recursos: *Paquete* y *actualización*. Además, se han actualizado las versiones de varios recursos existentes.



=== RBAC mejorado con granularidad de espacio de nombres

Al enlazar un rol a un usuario asociado, es posible limitar los espacios de nombres a los que tiene acceso el usuario. Consulte la referencia *Role Binding API* y. link:../additional/rbac.html["Seguridad RBAC"] si quiere más información.



=== Extracción del cucharón

Puede retirar un cucharón cuando ya no sea necesario o no funcione correctamente.



=== Compatibilidad con Cloud Volumes ONTAP

Cloud Volumes ONTAP ahora es compatible como back-end de almacenamiento.



=== Mejoras adicionales del producto

Hay varias mejoras adicionales en las dos implementaciones de productos de Astra Control, que incluyen:

* Entrada genérica para Astra Control Center
* Clúster privado en AKS
* Compatibilidad con Kubernetes 1.22
* Soporte para la cartera de Tanzania de VMware


Consulte la página *Novedades* en los sitios de documentación de Astra Control Center y Astra Control Service.

.Información relacionada
* https://docs.netapp.com/us-en/astra-control-center-2204/release-notes/whats-new.html["Astra Control Center 22.04: Novedades"^]




== 14 de diciembre de 2021 (21.12)

Esta versión incluye una ampliación de LA API DE REST junto con un cambio en la estructura de documentación para respaldar mejor la evolución de Astra Control con las futuras actualizaciones de versiones.



=== Separe la documentación de Astra Automation para cada versión de Astra Control

Cada versión de Astra Control incluye una API de REST distinta que se ha mejorado y adaptado a las funciones de la versión específica. La documentación de cada versión de la API REST de Astra Control ya está disponible en su propio sitio web dedicado junto con el repositorio de contenido de GitHub asociado. El sitio del documento principal https://docs.netapp.com/us-en/astra-automation/["Automatización de control de Astra"^] siempre contiene la documentación de la versión más reciente. Consulte link:../aa-earlier-versions.html["Versiones anteriores de la documentación de Astra Control Automation"] para obtener información acerca de versiones anteriores.



=== Expansión de los tipos de recursos de REST

El número de tipos de recursos DE REST ha seguido aumentando con un énfasis en los enlaces de ejecución y los back-ends de almacenamiento. Los nuevos recursos incluyen: Cuenta, enlace de ejecución, origen de gancho, anulación de gancho de ejecución, nodo de clúster, gestión del back-end de almacenamiento, espacio de nombres, dispositivo de almacenamiento y nodo de almacenamiento. Consulte link:../endpoints/resources.html["Recursos"] si quiere más información.



=== Kit de desarrollo de software Astra Control Python de NetApp

Astra Control Python SDK de NetApp es un paquete de código abierto que facilita el desarrollo de código de automatización para su entorno de Astra Control. El núcleo es Astra SDK, que incluye un conjunto de clases para abstraer la complejidad de las llamadas API REST. También hay un script de kit de herramientas para ejecutar tareas administrativas específicas empaquetando y extrayendo las clases de Python. Consulte link:../python/astra_toolkits.html["Kit de desarrollo de software Astra Control Python de NetApp"] si quiere más información.

.Información relacionada
* https://docs.netapp.com/us-en/astra-control-center-2112/release-notes/whats-new.html["Astra Control Center 21.12: Novedades"^]




== 5 de agosto de 2021 (21.08)

Esta versión incluye la introducción de un nuevo modelo de puesta en marcha de Astra y una importante ampliación de LA API DE REST.



=== Modelo de implementación de Astra Control Center

Además de la oferta existente de Astra Control Service que se proporciona como servicio de cloud público, esta versión incluye también el modelo de puesta en marcha en las instalaciones de Astra Control Center. Puede instalar Astra Control Center en sus instalaciones para gestionar su entorno local de Kubernetes. Los dos modelos de puesta en marcha de Astra Control comparten la misma API DE REST, con pequeñas diferencias observadas en la documentación.



=== Expansión de los tipos de recursos de REST

El número de recursos a los que se puede acceder mediante la API REST de Astra Control se ha ampliado enormemente y muchos de los nuevos recursos proporcionan una base para la oferta local de Astra Control Center. Los nuevos recursos incluyen: ASUP, autorización, función, licencia, configuración suscripción, bloque, cloud, clúster, clúster gestionado, storage backend y clase de almacenamiento. Consulte link:../endpoints/resources.html["Recursos"] si quiere más información.



=== Puntos finales adicionales compatibles con la implementación de Astra

Además de los recursos REST ampliados, hay varios otros extremos API nuevos disponibles para admitir una puesta en marcha de Astra Control.

Soporte para openapi:: Los extremos de OpenAPI proporcionan acceso al documento JSON de OpenAPI actual y a otros recursos relacionados.
Compatibilidad con OpenMetrics:: Los extremos de OpenMetrics proporcionan acceso a las métricas de cuentas mediante el recurso OpenMetrics.


.Información relacionada
* https://docs.netapp.com/us-en/astra-control-center-2108/release-notes/whats-new.html["Astra Control Center 21.08: Novedades"^]




== 15 de abril de 2021 (21.04)

Esta versión incluye las siguientes funciones y mejoras nuevas.



=== Introducción de la API de REST

La API REST de Astra Control está disponible para su uso con la oferta de Astra Control Service. Se ha creado a partir de tecnologías DE REST y prácticas recomendadas vigentes. La API proporciona una base para la automatización de sus implementaciones de Astra e incluye las siguientes funciones y ventajas.

Recursos:: Hay catorce tipos de recursos DE REST disponibles.
Acceso de token de API:: El acceso a la API DE REST se proporciona mediante un token de acceso de la API que se puede generar en la interfaz de usuario web de Astra. El token de API proporciona acceso seguro a la API.
Soporte para colecciones:: Hay un amplio conjunto de parámetros de consulta que se pueden utilizar para tener acceso a las colecciones de recursos. Algunas de las operaciones admitidas son el filtrado, la ordenación y la paginación.

