---
sidebar: sidebar 
permalink: workflows_infra/wf_add_cluster.html 
keywords:  
summary: Puede añadir un clúster para que Astra lo gestione. 
---
= Añada un clúster mediante credenciales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede añadir un clúster para que Astra lo gestione. A partir de la versión Astra 22.11, puede añadir un clúster con Astra Control Center y Astra Control Service.


NOTE: No es necesario añadir un clúster cuando se usa un servicio de Kubernetes de uno de los principales proveedores de cloud (AKS, EKS, GKE).



== Paso 1: Obtenga el archivo kubeconfig

Necesita obtener una copia del archivo *kubconfig* de su administrador o servicio de Kubernetes.



== Paso 2: Preparar el archivo kubeconfig

Antes de utilizar el archivo *kubeconfig*, debe realizar las siguientes operaciones:

. Convertir archivo de formato YAML a JSON:
+
Si recibe el archivo kubeconfig con formato YAML, debe convertirlo a JSON.

. Codificar JSON en base64:
+
Debe codificar el archivo JSON en base64.



.Ejemplo
Aquí hay un ejemplo de la conversión del archivo kubeconfig de YAML a JSON y luego codificarlo en base64:

`yq -o=json ~/.kube/config | base64`



== Paso 3: Seleccione la nube

Realice el flujo de trabajo link:../workflows_infra/wf_list_clouds.html["Enumerar las nubes"] y seleccione el cloud donde se añadirá el clúster.


NOTE: La única nube que puede seleccionar es la *nube privada*.



== Paso 4: Crear una credencial

Realice la siguiente llamada a la API DE REST para crear una credencial mediante el archivo kubeconfig.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /accounts/{account_id}/core/v1/credenciales 
|===
.Ejemplo de curl
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/core/v1/credentials" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "type" :  "application/astra-credential",
  "version" : "1.1",
  "name" : "Cloud One",
  "keyType" : "kubeconfig",
  "keyStore" : {
    "base64": encoded_kubeconfig
  },
  "valid" : "true"
}
----


== Paso 5: Añada el clúster

Realice la siguiente llamada de API REST para añadir el clúster al cloud. El valor de `credentialID` El campo de entrada se obtiene de la llamada a la API DE REST en el paso anterior.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /accounts/{account_id}/topolog/v1/cloud/{cloud_id}/clusters 
|===
.Ejemplo de curl
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/topology/v1/clouds/<CLOUD_ID>/clusters" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "type" :  "application/astra-cluster",
  "version" : "1.1",
  "credentialID": credential_id
}
----