---
sidebar: sidebar 
permalink: workflows_infra/wf_man_cluster.html 
keywords:  
summary: Es posible gestionar un clúster de Kubernetes para poder realizar operaciones de protección de datos. 
---
= Gestione un clúster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible gestionar un clúster de Kubernetes para poder llevar a cabo la protección de datos.



== Paso 1: Seleccione el clúster que desea administrar

Realice el flujo de trabajo link:../workflows_infra/wf_list_clusters.html["Enumere los clústeres"] y seleccione el clúster que desee. La propiedad `managedState` del clúster debe ser `unmanaged`.



== Paso 2: De manera opcional, seleccione la clase de almacenamiento

Si lo desea, puede ejecutar el flujo de trabajo link:../workflows_infra/wf_list_storage_classes.html["Enumerar las clases de almacenamiento"] y seleccione la clase de almacenamiento que desee.


NOTE: Si no proporciona una clase de almacenamiento a la llamada para gestionar el clúster, se usará la clase de almacenamiento predeterminada.



== Paso 3: Administre el clúster

Realice la siguiente llamada API REST para gestionar el clúster.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="1,6"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /Accounts/{account_id}/topolog/v1/managedClusters 
|===
.Ejemplo de curl
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/topology/v1/managedClusters" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "type": "application/astra-managedCluster",
  "version": "1.0",
  "id": "d0fdf455-4330-476d-bb5d-4d109714e07d"
}
----