---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-settings-.html 
summary: Recuperar un ajuste 
---
= Recuperar un ajuste
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/settings/{setting_id}`#

Devuelve el recurso de la API de configuración almacenado en el cuerpo de respuesta JSON.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| setting_id | cadena | ruta | Verdadero  a| 
ID de la colección de ajustes a listar

|===


== Respuesta

[source]
----
Status: 200, Returns the stored Setting API resource in the JSON response body.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-setting"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| nombre | cadena | Verdadero  a| 
Cadena JSON que contiene un nombre para el ajuste, en notación jerárquica de puntos (.). Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63
* Esta cadena es validada internamente para prevenir ataques XSS, Unicode, directory traversal y SQL-injection. Este valor es especificado por el configmap que es cargado en tiempo de ejecución y no puede ser actualizado por el usuario.




| currentConfig | link:#type_json["tipo_json"] | Verdadero  a| 
Objeto JSON que contiene las claves y valores que componen la configuración actual para este ajuste. El contenido de este objeto debe ajustarse al esquema JSON contenido en el campo configSchema. Los valores por defecto son suministrados por el configmap. Después de que los valores por defecto sean modificados por el usuario, no serán sobrescritos.



| desiredConfig | link:#type_json["tipo_json"] | Falso  a| 
Objeto JSON que contiene claves y valores que conforman la configuración solicitada para esta configuración. El contenido de este objeto debe ajustarse al esquema JSON contenido en el campo configSchema. El objeto no existe hasta que se especifica. Cuando se especifica, esto hace que el servicio de características notifique al servicio correspondiente para solicitar que se pueda aplicar la configuración deseada. El servicio correspondiente puede entonces realizar la validación y aplicar la configuración deseada a la configuración actual.



| configSchema | link:#type_json_schema["type_json_schema"] | Verdadero  a| 
Objeto JSON que contiene el esquema JSON para la propiedad config en este recurso. Debe ajustarse a JSON Schema Draft 7. Si los valores config están presentes en el recurso, la validación contra el configSchema indicado es obligatoria. Como convención común, se recomienda que las configuraciones tengan un campo "isEnabled", cuando sea apropiado. El campo "isEnabled" contiene un valor que indica si la configuración está activada ("true") o desactivada ("false").



| estado | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica el estado operativo de la aplicación. Los valores definidos son:

* "válido" - La configuración actual coincide con la configuración deseada.
* "pendiente" - Se está aplicando la configuración deseada.
* "error" - No se puede aplicar la configuración deseada.




| stateUnready | array[string] | Verdadero  a| 
Matriz JSON de cadenas JSON, cada una de las cuales indica un motivo por el que la configuración no se ha aplicado correctamente. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 127




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Se ajusta al esquema de metadatos de Astra Si no se especifica en la actualización, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-setting",
  "version": "1.1",
  "id": "ea510866-47d3-5130-8468-563df4cd6a28",
  "name": "astra.account.smtp",
  "currentConfig": {
    "credential": "",
    "isEnabled": "false",
    "port": 587,
    "relayServer": "smtp.sendgrid.net"
  },
  "configSchema": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "astra.account.smtp",
    "type": "object",
    "properties": {
      "credential": {
        "type": "string",
        "description": "The credential ID for SMTP authentication."
      },
      "isEnabled": {
        "type": "string",
        "description": "This property determines if this setting is enabled or not."
      },
      "port": {
        "type": "integer",
        "description": "The SMTP port. For an unencrypted or a TLS connection, use port 25, 2525, or 587."
      },
      "relayServer": {
        "type": "string",
        "description": "This setting is sometimes referred to as the external SMTP server or the SMTP relay."
      }
    },
    "additionalProperties": false,
    "required": [
      "relayServer",
      "port",
      "isEnabled"
    ]
  },
  "state": "valid",
  "stateUnready": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Respuesta

[source]
----
Status: 503, Service unavailable
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/41",
  "title": "Service not ready",
  "detail": "Currently, the service can't respond to this request.",
  "status": "503"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
tipo_json

Objeto JSON que contiene las claves y valores que componen la configuración actual para este ajuste. El contenido de este objeto debe ajustarse al esquema JSON contenido en el campo configSchema. Los valores por defecto son suministrados por el configmap. Después de que los valores por defecto sean modificados por el usuario, no serán sobrescritos.

[role="api-collapsible-fifth-title"]
tipo_json

Objeto JSON que contiene claves y valores que conforman la configuración solicitada para esta configuración. El contenido de este objeto debe ajustarse al esquema JSON contenido en el campo configSchema. El objeto no existe hasta que se especifica. Cuando se especifica, esto hace que el servicio de características notifique al servicio correspondiente para solicitar que se pueda aplicar la configuración deseada. El servicio correspondiente puede entonces realizar la validación y aplicar la configuración deseada a la configuración actual.

[role="api-collapsible-fifth-title"]
propiedades

[role="api-collapsible-fifth-title"]
type_json_schema

Objeto JSON que contiene el esquema JSON para la propiedad config en este recurso. Debe ajustarse a JSON Schema Draft 7. Si los valores config están presentes en el recurso, la validación contra el configSchema indicado es obligatoria. Como convención común, se recomienda que las configuraciones tengan un campo "isEnabled", cuando sea apropiado. El campo "isEnabled" contiene un valor que indica si la configuración está activada ("true") o desactivada ("false").

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| $schema | cadena | Verdadero  a| 



| tipo | cadena | Verdadero  a| 



| propiedades | link:#properties["propiedades"] | Verdadero  a| 



| additionalProperties | booleano | Verdadero  a| 



| obligatorio | array[string] | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Se ajusta al esquema de metadatos de Astra Si no se especifica en la actualización, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====