---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-core-v1-groups-users-unreadnotifications-.html 
summary: Recupera una notificación no leída para un usuario en un grupo 
---
= Recupera una notificación no leída para un usuario en un grupo
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/groups/{group_id}/users/{user_id}/unreadNotifications/{unreadNotification_id}`#

Devuelve el recurso Unread Notification API almacenado en el cuerpo de respuesta JSON.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| grupo_id | cadena | ruta | Verdadero  a| 
ID del recurso de grupo contenedor



| user_id | cadena | ruta | Verdadero  a| 
ID del recurso de usuario contenedor



| unreadNotification_id | cadena | ruta | Verdadero  a| 
ID de la colección unreadNotification que se va a listar

|===


== Respuesta

[source]
----
Status: 200, Returns the stored Unread Notification API resource in the JSON response body.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-unreadNotification"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| notificationID | cadena | Verdadero  a| 
Cadena JSON que contiene un ID de notificación que debe ser marcado como leído por el usuario que crea la marca. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| sequenceCount | número | Verdadero  a| 
Número JSON que contiene un recuento de secuencias asociado a la notificación especificada por el ID de notificación.



| gravedad | cadena | Verdadero  a| 
Cadena JSON que contiene uno de los siguientes valores que indican la gravedad del evento. Los valores definidos son:

* "cleared" - Indica que un evento previamente reportado que describe una condición ya no está activo. Un evento con gravedad "cleared" utilizará el mismo resumen e ID de correlación para permitir su cotejo
* "indeterminado" - Indica que no se puede determinar la gravedad
* "informativo" - Indica un cambio de estado esperado y normal (no definido en X.733)
* "warning" - Indica la detección de un fallo potencial o inminente que afecta al servicio antes de que se produzcan efectos significativos
* "crítico" - Indica que se ha producido una situación que afecta al servicio y se requiere una acción correctiva inmediata




| metadatos | link:#type_astra_metadata["tipo_astra_metadatos"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-unreadNotification",
  "version": "1.0",
  "id": "10df997b-629e-50f8-bc5f-a18b9a4ac5f6",
  "notificationID": "4080cf5f-2261-4130-b8fb-8432e2e553e6",
  "sequenceCount": 48923,
  "severity": "warning",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_metadatos

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Verdadero  a| 



| CreationTimestamp | cadena | Verdadero  a| 



| Modificación.Marca de hora | cadena | Verdadero  a| 



| CreatedBy | cadena | Verdadero  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====