---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-core-v1-users-groups.html 
summary: Listar los grupos de un usuario 
---
= Listar los grupos de un usuario
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/users/{user_id}/groups`#

Devuelve una matriz JSON de todos los recursos coincidentes de la colección. Si se especifican campos individuales en la solicitud, la matriz JSON de elementos contendrá los campos solicitados para cada recurso coincidente en el orden especificado.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| user_id | cadena | ruta | Verdadero  a| 
ID del recurso de usuario contenedor



| incluya | cadena | consulta | Falso  a| 
Indica qué campos deben devolverse al listar una colección.

Ejemplos de URL: "include=id", "include=id,name"

Ejemplos OpenAPI: "id"

* ejemplo: id,authProvider,authID




| límite | cadena | consulta | Falso  a| 
Indica el número máximo de recursos a devolver al listar una colección.

Ejemplos de URL: "limit=2"

Ejemplos OpenAPI: "2"



| filtro | cadena | consulta | Falso  a| 
Indica qué campos deben coincidir para devolver un recurso al listar una colección.

Los operadores admitidos son:

* eq - Igualdad
* lt/gt - Menor que/Mayor que
* lte/gte - Menor o igual que/Mayor o igual que


Ejemplo de URL: "filter=field%20eq%20%27value%27"

Ejemplos OpenAPI: "field eq 'value'"



| OrderBy | cadena | consulta | Falso  a| 
Indica el orden de clasificación de los recursos al listar una colección.

Ejemplos de URL: "orderBy=name", "orderBy=name%20desc"

Ejemplos OpenAPI: "name desc"



| omitir | cadena | consulta | Falso  a| 
Indica el número de recursos que deben omitirse al listar una colección.

Ejemplos de URL: "skip=1"

Ejemplos OpenAPI: "1"



| cuente | cadena | consulta | Falso  a| 
Indica si se debe devolver el número total de recursos en el objeto de metadatos.

Ejemplos de URL: "count=true"

Ejemplos de OpenAPI: "true"



| continuar |  | consulta | Falso  a| 
Indica el token desde el que reanudar el listado.

Ejemplos de URL: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

Ejemplos OpenAPI: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>

|===


== Respuesta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| artículos | array[Cualquiera de: link:#group_1_1_get_response_body["group_1.1_get_response_body"], array[]] | Verdadero  a| 



| metadatos | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadero  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-groups",
  "version": "1.1",
  "items": [
    [
      "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa",
      "ldap",
      "CN=Testers,CN=groups,DC=example,DC=com"
    ],
    [
      "e324ec3a-706d-4f57-a95d-1d88c03e7b73",
      "ldap",
      "CN=Admins,CN=groups,DC=example,DC=com"
    ],
    [
      "3070c84d-129b-4017-82a8-2c26a42dd77e",
      "ldap",
      "CN=SREs,CN=groups,DC=example,DC=com"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 500, Internal server error
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/34",
  "title": "Internal server error",
  "detail": "The server was unable to process this request.",
  "status": "500"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
group_1.1_get_response_body

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-group"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| nombre | cadena | Verdadero  a| 
El nombre del recurso de grupo. Si no se especifica al crear, el valor se establecerá en

* primer Common Name (CN) Relative Distinguished Names (RDN) si se encuentra en el authID,
* authID, en caso contrario. Si no se especifica en la actualización, el valor se conservará sin modificaciones. Los valores definidos son:
* Longitud mínima: 1
* Longitud máxima: 2048




| authProvider | cadena | Verdadero  a| 
El proveedor de autenticación para el recurso de grupo. Los valores definidos son:

* "ldap"




| authID | cadena | Verdadero  a| 
El nombre distintivo (DN) de un grupo LDAP. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 2048




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| continuar | cadena | Falso  a| 



| cuente | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====