---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-schedules-.html 
summary: Recupera un horario 
---
= Recupera un horario
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/schedules/{schedule_id}`#

Devuelve el recurso de Schedule API almacenado en el cuerpo de la respuesta JSON.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| app_id | cadena | ruta | Verdadero  a| 
ID del recurso que contiene la aplicación



| schedule_id | cadena | ruta | Verdadero  a| 
ID de la colección de horarios a listar

|===


== Respuesta

[source]
----
Status: 200, Returns the stored Schedule API resource in the JSON response body.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-schedule"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| nombre | cadena | Verdadero  a| 
Cadena JSON que contiene el nombre del horario. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63




| habilitado | cadena | Verdadero  a| 
Cadena JSON que indica si un horario está activo. Los valores definidos son:

* "true" - El horario está activo
* "false" - El horario no está activo Si no se especifica, el valor por defecto es "true".




| granularidad | cadena | Verdadero  a| 
Cadena JSON que indica la granularidad de la programación. Los valores definidos son:

* "por hora"
* "diario"
* "semanal"
* "mensual"
* "personalizado"




| minuto | cadena | Verdadero  a| 
Cadena JSON que contiene un valor numérico que indica el minuto de la hora (0 - 59) para ejecutar la programación. Los valores definidos son:

* La expresión regular definida es: "^[0-9]|[1-5][0-9]$" Este campo está presente si la granularidad está configurada como "hourly", "daily", "weekly" o "monthly". Se devolverá con el valor "0" para los horarios personalizados.




| hora | cadena | Falso  a| 
Cadena JSON que contiene un valor numérico que indica la hora del día (0 - 23) para ejecutar el horario. Los valores definidos son:

* La expresión regular definida es: "^[0-9]|[1][0-9]|[2][0-3]$" Este campo está presente si la granularidad está configurada como "daily", "weekly" o "monthly".




| dayOfWeek | cadena | Falso  a| 
Cadena JSON que contiene un valor numérico que indica el día de la semana (0-7) para ejecutar la programación. Los valores definidos son:

* La expresión regular definida es: "^[0-7]$" Este campo solo está presente si la granularidad es "weekly".




| dayOfMonth | cadena | Falso  a| 
Cadena JSON que contiene un valor numérico que indica el día del mes (1-31) para ejecutar la programación. Los valores definidos son:

* La expresión regular definida es: "^[1-9]|[1-2][0-9]|[3][0-1]$" Este campo solo está presente si la granularidad es "monthly".




| recurrenceRule | cadena | Falso  a| 
Cadena JSON que contiene una RFC-5545 Sección 3.8.5.3. Regla de recurrencia. Para el parámetro DTSTART, solo se admiten marcas de tiempo UTC (indicadas por el sufijo "Z") y solo se admiten marcas de tiempo anteriores a la hora actual. Para las partes de la regla RECUR, "FREQ" e "INTERVAL" son las únicas partes de la regla admitidas. Para la parte de la regla FREQ, "MINUTELY" y "HOURLY" son los únicos valores admitidos. Este campo solo está presente si la granularidad está configurada como "custom".



| snapshotRetention | cadena | Verdadero  a| 
Cadena JSON que contiene un valor numérico positivo que indica cuántas instantáneas conservar. Cero indica que las instantáneas deben eliminarse después de hacer una copia de seguridad. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63
* La expresión regular definida es: "^(0|([1-9][0-9]*))$"




| backupRetention | cadena | Verdadero  a| 
Cadena JSON que contiene un valor numérico positivo que indica cuántas copias de seguridad se deben conservar. Cero indica que no se deben crear copias de seguridad. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63
* La expresión regular definida es: "^(0|([1-9][0-9]*))$"




| bucketID | cadena | Falso  a| 
Cadena JSON que contiene un ID de bucket opcional que indica dónde debe almacenarse el backup al crearla. Si no se especifica, se usará un bucket seleccionado por el sistema. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| replicar | cadena | Falso  a| 
Cadena JSON que indica si la planificación activa la replicación AppMirror para cada snapshot. Solo tiene efecto si la aplicación tiene una relación AppMirror definida. Los valores definidos son:

* "true" - El horario activa la replicación AppMirror
* "false" - El horario no activa la replicación AppMirror Si no se especifica, el valor por defecto es "false".




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-schedule",
  "version": "1.3",
  "id": "49cbc480-5f7d-51e2-8f30-52b9a83a03b1",
  "name": "Backup Schedule",
  "enabled": "true",
  "granularity": "monthly",
  "minute": "0",
  "hour": "0",
  "dayOfMonth": "1",
  "snapshotRetention": "12",
  "backupRetention": "12",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====