---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-entitlements-.html 
summary: Recupera un derecho 
---
= Recupera un derecho
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/entitlements/{entitlement_id}`#

Devuelve el recurso de la Entitlement API almacenado en el cuerpo de la respuesta JSON.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| entitlement_id | cadena | ruta | Verdadero  a| 
ID de la colección de derechos a listar

|===


== Respuesta

[source]
----
Status: 200, Returns the stored Entitlement API resource in the JSON response body.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-entitlement"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| asignación | cadena | Falso  a| 
Cadena JSON que contiene el ID del objeto al que se asigna el derecho. Solo está presente cuando se asigna el derecho. El contenido de la cadena no es validado por el esquema.



| producto | cadena | Falso  a| 
Cadena JSON que contiene la cadena del producto extraída de la licencia o suscripción. Contenido de la cadena no validado por el esquema.



| productVersion | cadena | Falso  a| 
Cadena JSON que contiene la cadena de versión extraída de la licencia o suscripción. Contenido de la cadena no validado por el esquema.



| entitlementType | cadena | Verdadero  a| 
Cadena JSON que contiene el tipo de derecho. Se extrae de la licencia o suscripción. El contenido de la cadena no es validado por el esquema.



| entitlementValue | cadena | Verdadero  a| 
Cadena JSON que contiene la capacidad asociada al entitlement. Contenido de la cadena no validado por el esquema.



| entitlementConsumption | cadena | Falso  a| 
Cadena JSON que contiene la cantidad de capacidad asociada con la asignación de derechos que está actualmente en uso. Contenido de la cadena no validado por el esquema.



| sourceLicense | cadena | Falso  a| 
Cadena JSON que contiene el ID del objeto de licencia del que procede el derecho. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| sourceSubscription | cadena | Falso  a| 
Cadena JSON que contiene el ID del objeto de suscripción del que procede el entitlement. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| validFromTimestamp | cadena | Falso  a| 
Cadena JSON que contiene una marca de tiempo que indica cuándo el derecho se vuelve válido. Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| validUntilTimestamp | cadena | Falso  a| 
Cadena JSON que contiene una marca de tiempo que indica cuándo deja de ser válido el entitlement. Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| metadatos | link:#type_astra_metadata["tipo_astra_metadatos"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-entitlement",
  "version": "1.0",
  "id": "8bdafc19-bde6-5f45-9808-4893c845c9f5",
  "product": "Astra SDS",
  "productVersion": "1.0",
  "entitlementType": "capacity",
  "entitlementValue": "2",
  "entitlementConsumption": "1",
  "sourceLicense": "c8aa757a-5318-489f-8134-a2a1a6956a3e",
  "validFromTimestamp": "2020-08-06T00:00:00.000000Z",
  "validUntilTimestamp": "2021-08-06T00:00:00.000000Z",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_metadatos

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Verdadero  a| 



| CreationTimestamp | cadena | Verdadero  a| 



| Modificación.Marca de hora | cadena | Verdadero  a| 



| CreatedBy | cadena | Verdadero  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====