---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-clouds-clusters-storageclasses.html 
summary: Enumera las clases de almacenamiento de una nube 
---
= Enumera las clases de almacenamiento de una nube
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clouds/{cloud_id}/clusters/{cluster_id}/storageClasses`#

Devuelve una matriz JSON de todos los recursos coincidentes de la colección. Si se especifican campos individuales en la solicitud, la matriz JSON de elementos contendrá los campos solicitados para cada recurso coincidente en el orden especificado.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| cloud_id | cadena | ruta | Verdadero  a| 
ID del recurso de nube que lo contiene



| cluster_id | cadena | ruta | Verdadero  a| 
ID del recurso de clúster que lo contiene



| incluya | cadena | consulta | Falso  a| 
Indica qué campos deben devolverse al listar una colección.

Ejemplos de URL: "include=id", "include=id,name"

Ejemplos OpenAPI: "id"

* ejemplo: id,name




| límite | cadena | consulta | Falso  a| 
Indica el número máximo de recursos a devolver al listar una colección.

Ejemplos de URL: "limit=2"

Ejemplos OpenAPI: "2"

|===


== Respuesta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| artículos | array[Cualquiera de: link:#storageClass_1_1_get_response_body["storageClass_1.1_get_response_body"], array[]] | Verdadero  a| 



| metadatos | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadero  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-storageClasses",
  "version": "1.1",
  "items": [
    [
      "e280ff62-be35-4f31-a31b-a210a1ad1b33",
      "my-storage-class"
    ],
    [
      "e8507dad-d33f-44b3-9c15-ec55ba6f6473",
      "standard"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_metadatos

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Verdadero  a| 



| CreationTimestamp | cadena | Verdadero  a| 



| Modificación.Marca de hora | cadena | Verdadero  a| 



| CreatedBy | cadena | Verdadero  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
storageClass_1.1_get_response_body

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-storageClass"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| nombre | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica el nombre de la clase de almacenamiento. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 255




| aprovisionador | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica el provisioner asociado a la clase de almacenamiento. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 255




| disponible | cadena | Verdadero  a| 
Cadena JSON que indica si la clase de almacenamiento está disponible para el clúster o si puede añadirse al clúster cuando está bajo gestión. Los valores definidos son:

* "available" - La clase de almacenamiento está disponible para su uso
* "eligible" - La clase de almacenamiento es elegible para ser utilizada por el cluster cuando está bajo gestión
* "ineligible" - La clase de almacenamiento no es elegible para ser utilizada por el clúster cuando está bajo gestión




| allowVolumeExpansion | cadena | Verdadero  a| 
Cadena JSON que indica si la clase de almacenamiento permite la expansión del volumen. Los valores definidos son:

* "true" - La clase de almacenamiento permite la expansión del volumen
* "false" - La clase de almacenamiento no permite la ampliación del volumen
* "no disponible" - Se desconoce si la clase de almacenamiento permite la ampliación del volumen




| reclaimPolicy | cadena | Verdadero  a| 
Cadena JSON que contiene un valor específico de la nube que indica la política de retención de la clase de almacenamiento. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 255




| volumeBindingMode | cadena | Verdadero  a| 
Cadena JSON que contiene un valor específico de la nube que indica el modo de vinculación para la clase de almacenamiento. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 255




| isDefault | cadena | Falso  a| 
Cadena JSON que indica si la clase de almacenamiento contiene la anotación por defecto. Los valores definidos son:

* "true" - La clase de almacenamiento contiene la anotación por defecto




| maxSnapshotCount | número | Falso  a| 
Número JSON que indica cuántas instantáneas se admiten. Esta información se adjunta a las clases de almacenamiento proporcionadas por NetApp.



| maxBackupCount | número | Falso  a| 
Número JSON que indica cuántas copias de seguridad se admiten. Esta información se adjunta a las clases de almacenamiento proporcionadas por NetApp.



| precio | cadena | Falso  a| 
Cadena JSON que indica las unidades monetarias por unidad de tiempo para la clase de almacenamiento. Esta información se adjunta a las clases de almacenamiento proporcionadas por NetApp. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63




| divisa | cadena | Falso  a| 
Cadena JSON que indica el código ISO 4217 de tres letras para la moneda en la que se mide el precio. Esta información se adjunta a las clases de almacenamiento proporcionadas por NetApp. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 255




| rendimiento | número | Falso  a| 
Número JSON que indica el objetivo de nivel de servicio (SLO) de rendimiento en MBps. Esta información se adjunta a las clases de almacenamiento proporcionadas por NetApp.



| resiliencia | cadena | Falso  a| 
Cadena JSON que indica la configuración de resiliencia para el almacenamiento. Esta información se adjunta a las clases de almacenamiento proporcionadas por NetApp. Los valores definidos son:

* "regional" - El volumen dejará de estar disponible si una región determinada deja de estar disponible
* "multisitio" - El volumen seguirá estando disponible si una región determinada deja de estar disponible




| metadatos | link:#type_astra_metadata["tipo_astra_metadatos"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| continuar | cadena | Falso  a| 



| cuente | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====