---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-credentials.html 
summary: Lista todas las credenciales 
---
= Lista todas las credenciales
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/credentials`#

Devuelve una matriz JSON de todos los recursos coincidentes de la colección. Si se especifican campos individuales en la solicitud, la matriz JSON de elementos contendrá los campos solicitados para cada recurso coincidente en el orden especificado.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| continuar |  | consulta | Falso  a| 
Indica el token desde el que reanudar el listado.

Ejemplos de URL: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

Ejemplos OpenAPI: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>



| filtro | cadena | consulta | Falso  a| 
Indica qué campos deben coincidir para devolver un recurso al listar una colección.

Los operadores admitidos son:

* eq - Igualdad
* lt/gt - Menor que/Mayor que
* lte/gte - Menor o igual que/Mayor o igual que


Ejemplo de URL: "filter=field%20eq%20%27value%27"

Ejemplos OpenAPI: "field eq 'value'"



| incluya | cadena | consulta | Falso  a| 
Indica qué campos deben devolverse al listar una colección.

Ejemplos de URL: "include=id", "include=id,name"

Ejemplos OpenAPI: "id"

* ejemplo: id,name




| límite | cadena | consulta | Falso  a| 
Indica el número máximo de recursos a devolver al listar una colección.

Ejemplos de URL: "limit=2"

Ejemplos OpenAPI: "2"



| OrderBy | cadena | consulta | Falso  a| 
Indica el orden de clasificación de los recursos al listar una colección.

Ejemplos de URL: "orderBy=name", "orderBy=name%20desc"

Ejemplos OpenAPI: "name desc"

|===


== Respuesta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| artículos | array[Cualquiera de: link:#credential_1_1_get_response_body["credential_1.1_get_response_body"], array[]] | Verdadero  a| 



| metadatos | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadero  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credentials",
  "version": "1.1",
  "items": [
    [
      "f97f3441-075e-4f9b-9d1e-47f9f62a3fc4",
      "myCert"
    ],
    [
      "5e365b4d-034f-4f13-95ef-d3a7fbc0df3d",
      "kubeconfig"
    ],
    [
      "11ceb350-1999-4b79-80a6-46a980a27856",
      "password"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
credential_1.1_get_response_body

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-credential"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| nombre | cadena | Verdadero  a| 
Cadena JSON que contiene un nombre especificado por el usuario. Cuando se crea una credencial para un usuario, el nombre se establecerá con el UUID de ese usuario. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 127




| keyType | cadena | Falso  a| 
Cadena JSON que contiene un descriptor opcional del tipo de validación de datos especificado por el usuario para el contenido de keyStore. Restricciones de actualización ampliadas:

* Si un keyType no existe en el recurso y no se especifica en una actualización, el keyType no debe seguir existiendo en el recurso actualizado.
* Si un keyType no existe en el recurso y se especifica en una actualización, el keyType debe añadirse al recurso y debe realizarse la validación. Si la validación falla, la actualización fallará.
* Si existe un keyType en el recurso y no se especifica en una actualización, el keyType debe conservarse.
* Si existe un keyType en el recurso y se especifica en una actualización, y el keyType especificado coincide con el keyType existente, el keyType debe conservarse.
* Si existe un keyType en el recurso y se especifica en una actualización, y el keyType especificado es diferente del keyType existente, la actualización fallará. Los valores definidos son:
* "generic" - La credencial es una colección genérica de datos. Esto equivale a no incluir un keyType.
* La validación ampliada se realiza del siguiente modo:
* Debe existir una o varias cadenas en el keyStore.
* Cada cadena en keyStore debe tener un valor codificado en base64.
* "passwordHash" - La credencial es un hash de contraseña.
* La validación ampliada se realiza del siguiente modo:
* El nombre de la credencial debe ser único.
* El nombre de la credencial debe ser igual a un ID de recurso de usuario válido.
* El nombre de la credencial no debe alterarse.
* El recurso de usuario correspondiente debe tener un "authProvider" de "local".
* Debe existir una cadena "cleartext" dentro de keyStore con un valor que contenga una contraseña en texto claro codificada en base64:
* El texto claro de la contraseña debe ajustarse a la política de contraseñas de la cuenta.
* La contraseña se almacena como un hash.
* Debe existir una cadena "change" dentro de keyStore con un valor que contenga una cadena codificada en base64 "true" o "false".
* Una credencial del tipo passwordHash solo puede eliminarse si el ID de usuario indicado por el nombre no existe.
* "apikey" - La credencial es una clave API.
* La validación ampliada se realiza del siguiente modo:
* Debe existir una cadena "apikey" dentro de keyStore, con un valor que contenga una cadena arbitraria codificada en base64.
* "kubeconfig" - la credencial es una kubeconfig.
* La validación ampliada se realiza del siguiente modo:
* Debe existir una cadena "base64" dentro de keyStore, con un valor que contenga un archivo kubeconfig JSON codificado en base64.
* El archivo kubeconfig solo debe describir un único clúster.
* No pueden existir otros campos dentro de keyStore.
* "certificado" - la credencial es un certificado codificado PEM
* La validación ampliada se realiza del siguiente modo:
* Debe existir una cadena "certificate" dentro de keyStore, con un valor que contenga un certificado PEM codificado en base64.
* "privkey" - La credencial es una clave privada codificada en PEM.
* La validación ampliada se realiza del siguiente modo:
* Debe existir una cadena "privkey" dentro de keyStore, con un valor que contenga una clave privada PEM codificada en base64.
* "s3" - Indica que las credenciales son para acceso a Simple Storage Service (S3).
* La validación ampliada se realiza del siguiente modo:
* Debe existir una cadena ""accessKey"" dentro de keyStore con un valor que contenga una clave de acceso S3 codificada en base64.
* Debe existir una cadena ""accessSecret"" dentro de keyStore con un valor que contenga un secreto de acceso S3 codificado en base64.




| válido | cadena | Verdadero  a| 
Cadena JSON que describe si la credencial es válida para su uso. El valor por defecto, si se omite, es "true". Los valores definidos son:

* "true" - La credencial es apta para su uso.
* "false" - La credencial no debe utilizarse.




| validFromTimestamp | cadena | Falso  a| 
Cadena JSON que contiene una marca de tiempo que indica cuándo es válida la credencial. Se utilizan para la rotación de credenciales. Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| validUntilTimestamp | cadena | Falso  a| 
Cadena JSON que contiene una marca de tiempo que indica cuándo deja de ser válida la credencial. Se utilizan para la rotación de credenciales. Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| continuar | cadena | Falso  a| 



| cuente | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====