---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-appmirrors.html 
summary: Enumera los recursos de AppMirror para una app 
---
= Enumera los recursos de AppMirror para una app
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appMirrors`#

Devuelve una matriz JSON de todos los recursos coincidentes de la colección. Si se especifican campos individuales en la solicitud, la matriz JSON de elementos contendrá los campos solicitados para cada recurso coincidente en el orden especificado.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| app_id | cadena | ruta | Verdadero  a| 
ID del recurso que contiene la aplicación



| incluya | cadena | consulta | Falso  a| 
Indica qué campos deben devolverse al listar una colección.

Ejemplos de URL: "include=id", "include=id,name"

Ejemplos OpenAPI: "id"



| límite | cadena | consulta | Falso  a| 
Indica el número máximo de recursos a devolver al listar una colección.

Ejemplos de URL: "limit=2"

Ejemplos OpenAPI: "2"



| filtro | cadena | consulta | Falso  a| 
Indica qué campos deben coincidir para devolver un recurso al listar una colección.

Los operadores admitidos son:

* eq - Igualdad
* lt/gt - Menor que/Mayor que
* lte/gte - Menor o igual que/Mayor o igual que


Ejemplo de URL: "filter=field%20eq%20%27value%27"

Ejemplos OpenAPI: "field eq 'value'"

|===


== Respuesta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| artículos | array[Cualquiera de: link:#appMirror_1_1_get_response_body["appMirror_1.1_get_response_body"], array[]] | Verdadero  a| 



| metadatos | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadero  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appMirrors",
  "version": "1.1",
  "items": [
    {
      "type": "application/astra-appMirror",
      "version": "1.1",
      "id": "f1c98c2e-6391-42d3-8b21-3e75dac048a3",
      "sourceAppID": "efd639b6-fc92-4112-8841-0c0ab7890ae0",
      "sourceClusterID": "5789e026-c2e2-41e9-ab00-9766bcfa8951",
      "destinationAppID": "cd7b6d91-fc19-4983-a754-9a7bb4d80a7b",
      "destinationClusterID": "c5d023a9-4061-4a8a-bfbf-3be11ff06226",
      "namespaceMapping": [
        {
          "clusterID": "5789e026-c2e2-41e9-ab00-9766bcfa8951",
          "namespaces": [
            "ns1-src",
            "ns2-src"
          ]
        },
        {
          "clusterID": "c5d023a9-4061-4a8a-bfbf-3be11ff06226",
          "namespaces": [
            "ns1-dest",
            "ns2-dest"
          ]
        }
      ],
      "state": "established",
      "stateTransitions": [
        {
          "from": "establishing",
          "to": [
            "established",
            "deleting"
          ]
        },
        {
          "from": "established",
          "to": [
            "failingOver",
            "deleting"
          ]
        },
        {
          "from": "failingOver",
          "to": [
            "failedOver",
            "deleting"
          ]
        },
        {
          "from": "failedOver",
          "to": [
            "establishing",
            "deleting"
          ]
        },
        {
          "from": "deleting",
          "to": [
            "deleted"
          ]
        }
      ],
      "stateDesired": "established",
      "stateAllowed": [
        "failedOver",
        "deleted"
      ],
      "stateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/1",
          "title": "AppMirror relationship established",
          "detail": "The AppMirror relationship has been successfully established."
        }
      ],
      "healthState": "normal",
      "healthStateTransitions": [
        {
          "from": "indeterminate",
          "to": [
            "normal",
            "warning",
            "critical"
          ]
        },
        {
          "from": "normal",
          "to": [
            "indeterminate",
            "warning",
            "critical"
          ]
        },
        {
          "from": "warning",
          "to": [
            "indeterminate",
            "normal",
            "critical"
          ]
        },
        {
          "from": "critical",
          "to": [
            "indeterminate",
            "normal",
            "warning"
          ]
        }
      ],
      "healthStateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/2",
          "title": "SnapMirror syncing successfully",
          "detail": "All SnapMirror relationships are synchronizing as expected."
        }
      ],
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa"
      }
    },
    {
      "type": "application/astra-appMirror",
      "version": "1.1",
      "id": "114633f0-5b59-4bd7-adce-a9ba4423a1bd",
      "sourceAppID": "eaf8b854-211d-460a-ac18-d093d8e2ac70",
      "sourceClusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
      "destinationAppID": "e829c5e0-750f-44ad-a684-aee85be2c2bb",
      "destinationClusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
      "namespaceMapping": [
        {
          "clusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
          "namespaces": [
            "app-namespace"
          ],
          "role": "source"
        },
        {
          "clusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
          "namespaces": [
            "destination-app-namespace"
          ],
          "role": "destination"
        }
      ],
      "storageClasses": [
        {
          "storageClassName": "destination-sc",
          "clusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
          "role": "destination"
        }
      ],
      "state": "established",
      "stateTransitions": [
        {
          "from": "establishing",
          "to": [
            "established",
            "deleting"
          ]
        },
        {
          "from": "established",
          "to": [
            "failingOver",
            "deleting"
          ]
        },
        {
          "from": "failingOver",
          "to": [
            "failedOver",
            "deleting"
          ]
        },
        {
          "from": "failedOver",
          "to": [
            "establishing",
            "deleting"
          ]
        }
      ],
      "stateDesired": "established",
      "stateAllowed": [
        "failedOver",
        "deleted"
      ],
      "stateDetails": [],
      "transferState": "idle",
      "transferStateTransitions": [
        {
          "from": "transferring",
          "to": [
            "idle"
          ]
        },
        {
          "from": "idle",
          "to": [
            "transferring"
          ]
        }
      ],
      "transferStateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/24",
          "title": "Snapshot replication completed",
          "detail": "A snapshot was replicated to the destination.",
          "additionalDetails": {
            "completionTime": "2023-07-06T22:46:39Z",
            "snapshotID": "ae60820d-e963-4eab-8bb3-9159e9f012f0",
            "startTime": "2023-07-06T22:46:08Z"
          }
        }
      ],
      "healthState": "normal",
      "healthStateTransitions": [],
      "healthStateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/24",
          "title": "Snapshot replication completed",
          "detail": "A snapshot was replicated to the destination.",
          "additionalDetails": {
            "completionTime": "2023-07-06T22:46:39Z",
            "snapshotID": "ae60820d-e963-4eab-8bb3-9159e9f012f0",
            "startTime": "2023-07-06T22:46:08Z"
          }
        }
      ],
      "metadata": {
        "labels": [],
        "creationTimestamp": "2023-07-06T22:45:24Z",
        "modificationTimestamp": "2023-07-06T22:45:24Z",
        "createdBy": "cc420827-f968-4da7-9e72-df8a0fd52f94"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
namespaceMapping

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| clusterID | cadena | Falso  a| 
Identificador del clúster para el que se especifican los espacios de nombres. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| espacios de nombres | array[string] | Falso  a| 
Lista de espacios de nombres a utilizar en el clúster. Correlacionado con la otra lista de espacios de nombres del clúster por índice. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63
* Cumple con el esquema de etiquetas DNS 1123




| papel | cadena | Falso  a| 
El rol inicial para esta definición de espacio de nombres. Este parámetro es opcional excepto cuando se utiliza una configuración de replicación del mismo clúster. Los valores definidos son:

* "origen"
* "destino"


|===
[role="api-collapsible-fifth-title"]
storageClasses

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| clusterID | cadena | Falso  a| 
Identificador del clúster para el que se especifica la clase de almacenamiento. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| storageClassName | cadena | Falso  a| 
Nombre de la clase de almacenamiento que se utilizará al crear PVC en el clúster especificado en "clusterID". Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 255




| papel | cadena | Falso  a| 
El rol inicial para esta definición de clase de almacenamiento. Este parámetro es opcional excepto cuando se utiliza una configuración de replicación del mismo clúster. Los valores definidos son:

* "origen"
* "destino"


|===
[role="api-collapsible-fifth-title"]
type_astra_stateTransition

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| de | cadena | Verdadero  a| 



| a | array[string] | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
appMirror_1.1_get_response_body

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-appMirror"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| sourceAppID | cadena | Verdadero  a| 
Identificador de la aplicación de origen. Solo se actualiza al intercambiar el sourceAppID con el destinationAppID. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| sourceClusterID | cadena | Verdadero  a| 
Identificador del clúster gestionado que aloja la aplicación de origen. Este campo es de solo lectura y se determina en función del clúster de origen de la aplicación. Si se proporciona en una actualización, debe coincidir con el ID de clúster de la aplicación de origen, así que solo puede cambiar al intercambiar el sourceAppID con el destinationAppID. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| destinationAppID | cadena | Falso  a| 
Identificador de la aplicación de destino. No se puede proporcionar al crear porque se generará un nuevo app ID como parte de la inicialización de la relación. Solo se puede actualizar al intercambiar sourceAppID con destinationAppID. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| destinationClusterID | cadena | Verdadero  a| 
Identificador del clúster gestionado para alojar la aplicación de destino. Debe proporcionarse al crear porque determina en qué clúster se creará la aplicación de destino. Si se proporciona al actualizar, debe coincidir con el ID de clúster de la aplicación de destino, por lo que solo puede cambiar al intercambiar sourceAppID con destinationAppID. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| namespaceMapping | array[link:#namespaceMapping["namespaceMapping"]] | Falso  a| 
El espacio o espacios de nombres que se utilizarán al crear la aplicación de destino, correspondientes a los espacios de nombres de la aplicación de origen. Cada objeto JSON contiene los campos "clusterID" y "namespaces", donde el valor "clusterID" es el ID de cadena JSON del clúster de origen o destino, y el valor "namespaces" es una matriz JSON de cadenas JSON. Debe haber exactamente un objeto JSON por cada clúster, y los namespaces se correlacionarán por índice. Si no se proporciona, se utilizará el mismo namespace del clúster de origen en el clúster de destino. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 2




| storageClasses | array[link:#storageClasses["storageClasses"]] | Falso  a| 
La clase de almacenamiento que se utilizará en el clúster de destino al crear nuevas Reclamaciones de Volumen Persistente (PVC). Cada objeto JSON contiene los campos "clusterID" y "storageClassName", donde el valor "clusterID" es el ID de cadena JSON del clúster de origen o clúster de destino, y el valor "storageClassName" es la clase de almacenamiento que se utilizará al crear PVC en ese clúster. Si no se proporciona o si falta el valor para un clúster, se utilizará la clase de almacenamiento predeterminada para ese clúster. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 2




| estado | cadena | Verdadero  a| 
El estado de la relación. Los valores definidos son:

* "establecer" - Se está creando la relación.
* "establecido" - Se crea la relación.
* "failingOver" - La conmutación por error de la aplicación al clúster de destino está en curso.
* "failedOver" - Se ha completado la conmutación por error de la aplicación al clúster de destino.
* "borrando" - Se están limpiando los recursos creados por la relación.
* "deleted" - La relación se limpió y eliminó.




| stateTransitions | array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Falso  a| 
Transiciones de estado permitidas. Las siguientes transiciones de estado son posibles para este recurso:

* "estableciendo": "establecido", "borrando"
* "established": "failingOver", "deleting"
* "failingOver": "failedOver", "deleting"
* "failedOver": "establishing", "deleting"
* "borrar": "borrado"
* "borrado":




| stateDesired | cadena | Verdadero  a| 
Estado deseado para la relación. En el momento de la creación, el único valor válido es "establecido". Los valores definidos son:

* "establecido" - Se crea la relación.
* "failedOver" - Se ha completado la conmutación por error de la aplicación al clúster de destino.
* "deleted" - La relación se ha limpiado y eliminado correctamente.




| stateAllowed | array[string] | Falso  a| 
Estados que pueden solicitarse en un estado determinado. En cada estado definido pueden solicitarse los siguientes estados:

* "establishing": "established", "deleted"
* "establecido": "failedOver", "eliminado"
* "failingOver": "failedOver", "deleted"
* "failedOver": "established", "deleted"
* "borrar": "borrado"
* "deleted": "deleted"




| stateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Verdadero  a| 
Detalles adicionales sobre el estado actual, incluyendo por qué se alcanzó el estado actual. Si no hay detalles disponibles, esta matriz estará vacía. Los valores definidos son:

* Artículos mínimos: 0




| transferState | cadena | Falso  a| 
Estado de la transferencia de instantáneas actual o más reciente. Los valores definidos son:

* "transfiriendo" - Se ha creado una nueva instantánea y ahora se está replicando en el clúster de destino. Este estado también cubre las transferencias que han fallado en intentos anteriores y se están reintentando continuamente.
* "idle" - actualmente no hay ninguna transferencia en curso.




| transferStateTransitions | array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Falso  a| 
Transiciones de estado permitidas desde un estado definido dado. Las siguientes transiciones de estado son posibles para este recurso:

* "transferring": "idle"
* "inactivo": "transfiriendo"




| transferStateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falso  a| 
Detalles adicionales sobre el estado actual, incluyendo por qué se alcanzó el estado actual. Si no hay detalles disponibles, esta matriz estará vacía. Los valores definidos son:

* Artículos mínimos: 0




| healthState | cadena | Verdadero  a| 
Estado de salud del recurso. Los valores definidos son:

* "indeterminado" - No se puede determinar la salud del recurso (por ejemplo, por falta de conectividad)
* "normal" - El recurso no tiene problemas conocidos y puede prestar servicios de acuerdo con la especificación de la interfaz
* "advertencia" - El recurso tiene problemas conocidos que no le impiden prestar servicios de acuerdo con la especificación de la interfaz
* "crítico" - El recurso tiene problemas conocidos que le impiden prestar servicios de acuerdo con la especificación de la interfaz




| healthStateTransitions | array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Verdadero  a| 
Transiciones de estado permitidas desde un estado definido dado. Las siguientes transiciones de estado son posibles para este recurso:

* "indeterminate": "normal", "warning", "critical"
* "normal": "indeterminado", "advertencia", "crítico"
* "advertencia": "indeterminado", "normal", "crítico"
* "crítico": "indeterminado", "normal", "advertencia"




| healthStateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Verdadero  a| 
Detalles adicionales sobre el estado actual, incluyendo por qué se alcanzó el estado actual. Si no hay detalles disponibles, esta matriz estará vacía. Los valores definidos son:

* Artículos mínimos: 0




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| continuar | cadena | Falso  a| 



| cuente | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====