---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-k8s-v1-apps-appbackups-appassets-.html 
summary: Recuperar un activo de aplicación de una copia de seguridad de una app 
---
= Recuperar un activo de aplicación de una copia de seguridad de una app
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appBackups/{appBackup_id}/appAssets/{appAsset_id}`#

Devuelve el recurso de la API de Application Asset almacenado en el cuerpo de respuesta JSON.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| app_id | cadena | ruta | Verdadero  a| 
ID del recurso que contiene la aplicación



| appBackup_id | cadena | ruta | Verdadero  a| 
ID del recurso appBackup que lo contiene



| appAsset_id | cadena | ruta | Verdadero  a| 
ID de la colección appAsset que se va a listar

|===


== Respuesta

[source]
----
Status: 200, Returns the stored Application Asset API resource in the JSON response body.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-appAsset"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| assetType | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica qué tipo de activo se está describiendo como obtenido de Kubernetes. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 254




| CreationTimestamp | cadena | Verdadero  a| 
Cadena JSON que contiene una marca de tiempo que indica cuándo se crearon los metadatos de Kubernetes. Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| GVK | link:#GVK["GVK"] | Verdadero  a| 
Objeto JSON que contiene un grupo/versión/tipo de Kubernetes.



| recurso | link:#type_json["tipo_json"] | Falso  a| 
Objeto JSON que contiene todo el contenido de la definición del recurso Kubernetes.



| assetID | cadena | Verdadero  a| 
Cadena JSON que contiene un identificador asignado por Kubernetes. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| etiquetas | array[link:#labels["etiquetas"]] | Verdadero  a| 
Matriz JSON de objetos JSON, cada uno de los cuales contiene una etiqueta de Kubernetes asociada al activo. Si no hay detalles disponibles, esta matriz estará vacía.

* Elementos mínimos: 0




| assetName | cadena | Verdadero  a| 
Cadena JSON que contiene un nombre asignado por Kubernetes. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 254




| espacio de nombres | cadena | Falso  a| 
Cadena JSON que contiene un espacio de nombres asignado por Kubernetes. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 254




| metadatos | link:#type_astra_metadata["tipo_astra_metadatos"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appAsset",
  "version": "1.1",
  "id": "6415e851-b820-553b-9432-ebd057d1917d",
  "assetType": "Pod",
  "creationTimestamp": "2020-08-06T12:24:52.256624Z",
  "GVK": {
    "group": "apps",
    "kind": "Pod",
    "version": "v1"
  },
  "assetID": "93ec0c61-d993-4aa1-bb08-f4dcdd5e97f6",
  "labels": [
    {
      "name": "app",
      "value": "mediawiki"
    },
    {
      "name": "pod-template-hash",
      "value": "69c6fcf864"
    }
  ],
  "assetName": "mediawiki-69c6fcf864-2wx6l",
  "namespace": "wiki",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
GVK

Objeto JSON que contiene un grupo/versión/tipo de Kubernetes.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| grupo | cadena | Falso  a| 
Cadena JSON que contiene un identificador de grupo asignado por Kubernetes. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 254




| tipo | cadena | Falso  a| 
Cadena JSON que contiene un identificador de tipo asignado por Kubernetes. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 254




| versión | cadena | Falso  a| 
Cadena JSON que contiene un identificador de versión asignado por Kubernetes. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 254


|===
[role="api-collapsible-fifth-title"]
tipo_json

Objeto JSON que contiene todo el contenido de la definición del recurso Kubernetes.

[role="api-collapsible-fifth-title"]
etiquetas

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Cadena JSON que contiene el nombre de la etiqueta Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63
* La expresión regular definida es: "^([\S.]{1,253}\/)?([a-z0-9A-Z_.-]){1,63}$"




| valor | cadena | Verdadero  a| 
Cadena JSON que contiene el valor de la etiqueta Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63
* La expresión regular definida es: "^([a-z0-9A-Z_.-]){1,63}$"


|===
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_metadatos

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Verdadero  a| 



| CreationTimestamp | cadena | Verdadero  a| 



| Modificación.Marca de hora | cadena | Verdadero  a| 



| CreatedBy | cadena | Verdadero  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====