---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-managedclusters-apiresources-.html 
summary: Recuperar un recurso de la API K8s 
---
= Recuperar un recurso de la API K8s
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/managedClusters/{managedCluster_id}/apiResources/{apiResource_id}`#

Devuelve el recurso API específico en el cuerpo de respuesta JSON.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| managedCluster_id | cadena | ruta | Verdadero  a| 
ID del recurso managedCluster que lo contiene



| apiResource_id | cadena | ruta | Verdadero  a| 
ID de la colección apiResource que se va a listar

|===


== Respuesta

[source]
----
Status: 200, Returns the specific API resource in the JSON response body.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-apiResource"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| apiVersion | cadena | Verdadero  a| 
Cadena JSON que representa la versión de la API del recurso, establecida en o por Kubernetes. APIVersion define el esquema versionado para esta representación de objeto. Los servidores deben convertir los esquemas reconocidos al último valor interno y pueden rechazar los valores no reconocidos. Más información: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources[]



| tipo | cadena | Verdadero  a| 
Cadena JSON que representa el tipo de recurso, según lo establecido en o por Kubernetes. El campo kind utiliza mayúsculas y minúsculas y contiene un valor de cadena que representa el recurso REST que representa este objeto. Los servidores podrían deducirlo del endpoint al que el cliente envía solicitudes. No se puede actualizar. Más información: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds[]



| metadatos | link:#type_astra_metadata["tipo_astra_metadatos"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-apiResource",
  "version": "1.0",
  "id": "e280ff62-be35-4f31-a31b-a210a1ad1b33",
  "kind": "ClusterRole",
  "apiVersion": "rbac.authorization.k8s.io/v1",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_metadatos

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Verdadero  a| 



| CreationTimestamp | cadena | Verdadero  a| 



| Modificación.Marca de hora | cadena | Verdadero  a| 



| CreatedBy | cadena | Verdadero  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====