---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-upgrades.html 
summary: Lista de todas las actualizaciones 
---
= Lista de todas las actualizaciones
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/upgrades`#

Devuelve una matriz JSON de todos los recursos coincidentes de la colección. Si se especifican campos individuales en la solicitud, la matriz JSON de elementos contendrá los campos solicitados para cada recurso coincidente en el orden especificado.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| incluya | cadena | consulta | Falso  a| 
Indica qué campos deben devolverse al listar una colección.

Ejemplos de URL: "include=id", "include=id,name"

Ejemplos OpenAPI: "id"

* ejemplo: id,componentName,upgradeVersion




| límite | cadena | consulta | Falso  a| 
Indica el número máximo de recursos a devolver al listar una colección.

Ejemplos de URL: "limit=2"

Ejemplos OpenAPI: "2"



| filtro | cadena | consulta | Falso  a| 
Indica qué campos deben coincidir para devolver un recurso al listar una colección.

Los operadores admitidos son:

* eq - Igualdad
* lt/gt - Menor que/Mayor que
* lte/gte - Menor o igual que/Mayor o igual que


Ejemplo de URL: "filter=field%20eq%20%27value%27"

Ejemplos OpenAPI: "field eq 'value'"

|===


== Respuesta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| artículos | array[Cualquiera de: link:#upgrade_1_1_get_response_body["upgrade_1.1_get_response_body"], array[]] | Verdadero  a| 



| metadatos | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadero  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-upgrades",
  "version": "1.1",
  "items": [
    [
      "01982783-b1eb-4dca-a3fe-a385a3186c53",
      "acc",
      "21.07.1"
    ],
    [
      "0a5abab2-39b2-4101-87b9-0d9b8f537ca1",
      "acc",
      "21.07.2"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Se ajusta al esquema de metadatos de Astra Si no se especifica en la actualización, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
upgrade_1.1_get_response_body

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-upgrade"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| componentName | cadena | Verdadero  a| 
Cadena JSON que contiene el nombre del tipo de software que puede actualizarse. Los valores definidos son:

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| componentInstance | cadena | Verdadero  a| 
Cadena JSON que contiene el URI del componente que puede actualizarse. Los valores definidos son:

* Longitud mínima: 3
* Longitud máxima: 4095




| componentID | cadena | Verdadero  a| 
Cadena JSON que contiene un identificador único global del componente que puede actualizarse. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| upgradeVersion | cadena | Verdadero  a| 
Cadena JSON que contiene el SemVer del archivo de imagen de software al que se puede actualizar. Los valores definidos son:

* Cumple con el esquema SemVer




| currentVersion | cadena | Verdadero  a| 
Cadena JSON que contiene el SemVer actual de la entidad que se va a actualizar. Los valores definidos son:

* Cumple con el esquema SemVer




| dependencias | array[string] | Verdadero  a| 
Matriz JSON de cadenas JSON, cada una de las cuales contiene el UUID de una actualización que debe completarse antes de que esta actualización pueda continuar. Se utiliza para determinar qué actualizaciones se realizarán como requisitos previos y en qué orden. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| estado | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica el estado operativo de la actualización. Si la actualización automática está activada, las actualizaciones se iniciarán en el estado "scheduled". De lo contrario, las actualizaciones se iniciarán en el estado "proposed". Los valores definidos son:

* "no disponible" - La actualización no está disponible en este momento
* "propuesta" - La actualización está propuesta pero no se ejecutará automáticamente hasta que se apruebe
* "programada" - la actualización está aprobada pero no está lista para instalarse debido a dependencias, ventanas de tiempo o recursos disponibles
* "running" - La actualización está en curso
* "complete" - La actualización ha finalizado
* "failed" - La actualización no se ha completado




| stateDesired | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica el estado deseado para "state". Este campo solo se incluye cuando el usuario puede solicitar directamente un cambio en el estado del recurso. Los valores definidos son:

* "proposed" - La actualización no está aprobada y no debe realizarse
* "programada" - La actualización está aprobada y debe realizarse en el plazo especificado
* "en ejecución" - La actualización debe realizarse inmediatamente, independientemente de la ventana de tiempo




| stateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Verdadero  a| 
Matriz de objetos JSON que enumera detalles adicionales sobre el "estado" actual. Si no hay detalles disponibles, esta matriz estará vacía.

* Artículos mínimos: 0




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Se ajusta al esquema de metadatos de Astra Si no se especifica en la actualización, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| continuar | cadena | Falso  a| 



| cuente | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====