---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-ldapgroups.html 
summary: Listar todos los grupos LDAP 
---
= Listar todos los grupos LDAP
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/ldapGroups`#

Devuelve una matriz JSON de objetos JSON que contiene los resultados de la URL de la solicitud.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| incluya | cadena | consulta | Falso  a| 
Indica qué campos deben devolverse al listar una colección.

Ejemplos de URL: "include=id", "include=id,name"

Ejemplos OpenAPI: "id"

* ejemplo: id,cn,dn




| límite | cadena | consulta | Falso  a| 
Indica el número máximo de recursos a devolver al listar una colección.

Ejemplos de URL: "limit=2"

Ejemplos OpenAPI: "2"



| filtro | cadena | consulta | Falso  a| 
Indica qué campos deben coincidir para devolver un recurso al listar una colección.

Los operadores admitidos son:

* eq - Igualdad
* lt/gt - Menor que/Mayor que
* lte/gte - Menor o igual que/Mayor o igual que


Ejemplo de URL: "filter=field%20eq%20%27value%27"

Ejemplos OpenAPI: "field eq 'value'"



| continuar |  | consulta | Falso  a| 
Indica el token desde el que reanudar el listado.

Ejemplos de URL: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

Ejemplos OpenAPI: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>

|===


== Respuesta

[source]
----
Status: 200, Returns a JSON array of JSON objects containing the results of the request URL.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| artículos | array[Cualquiera de: link:#ldapGroup_1_0_get_response_body["ldapGroup_1.0_get_response_body"], array[]] | Verdadero  a| 



| metadatos | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadero  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-ldapGroups",
  "version": "1.0",
  "items": [
    [
      "4a461f57-70e6-5732-882e-8d5f684f15a1",
      "boulder_sysadmins",
      "cn=boulder_sysadmins,ou=groups,dc=example,dc=com"
    ],
    [
      "da4bbb6f-8f2c-57eb-a9cf-6eeffbf9e35d",
      "rtp_sysadmins",
      "cn=rtp_sysadmins,ou=groups,dc=example,dc=com"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/14",
  "title": "Unauthorized access",
  "detail": "The user isn't enabled.",
  "status": "403"
}
----
====


== Respuesta

[source]
----
Status: 406, Not acceptable
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/32",
  "title": "Unsupported content type",
  "detail": "The response can't be returned in the requested format.",
  "status": "406"
}
----
====


== Respuesta

[source]
----
Status: 500, Internal server error
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/34",
  "title": "Internal server error",
  "detail": "The server was unable to process this request.",
  "status": "500"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_metadatos

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Verdadero  a| 



| CreationTimestamp | cadena | Verdadero  a| 



| Modificación.Marca de hora | cadena | Verdadero  a| 



| CreatedBy | cadena | Verdadero  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
ldapGroup_1.0_get_response_body

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-ldapGroup"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| cn | cadena | Falso  a| 
Cadena JSON que representa el nombre del grupo LDAP. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63




| nombre distintivo | cadena | Falso  a| 
Cadena JSON que representa el nombre distintivo del grupo LDAP. Los valores definidos son:

* Cumple con RFC 4514




| metadatos | link:#type_astra_metadata["tipo_astra_metadatos"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Cumple con el esquema de metadatos Astra


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| continuar | cadena | Falso  a| 



| cuente | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====