---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-upgrades-.html 
summary: Recuperar una actualización 
---
= Recuperar una actualización
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/upgrades/{upgrade_id}`#

Devuelve el recurso de la API de actualizaciones almacenado en el cuerpo de respuesta JSON.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| upgrade_id | cadena | ruta | Verdadero  a| 
ID de la colección de actualizaciones a listar

|===


== Respuesta

[source]
----
Status: 200, Returns the stored Upgrade API resource in the JSON response body.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-upgrade"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| componentName | cadena | Verdadero  a| 
Cadena JSON que contiene el nombre del tipo de software que puede actualizarse. Los valores definidos son:

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| componentInstance | cadena | Verdadero  a| 
Cadena JSON que contiene el URI del componente que puede actualizarse. Los valores definidos son:

* Longitud mínima: 3
* Longitud máxima: 4095




| componentID | cadena | Verdadero  a| 
Cadena JSON que contiene un identificador único global del componente que puede actualizarse. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| upgradeVersion | cadena | Verdadero  a| 
Cadena JSON que contiene el SemVer del archivo de imagen de software al que se puede actualizar. Los valores definidos son:

* Cumple con el esquema SemVer




| currentVersion | cadena | Verdadero  a| 
Cadena JSON que contiene el SemVer actual de la entidad que se va a actualizar. Los valores definidos son:

* Cumple con el esquema SemVer




| dependencias | array[string] | Verdadero  a| 
Matriz JSON de cadenas JSON, cada una de las cuales contiene el UUID de una actualización que debe completarse antes de que esta actualización pueda continuar. Se utiliza para determinar qué actualizaciones se realizarán como requisitos previos y en qué orden. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| estado | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica el estado operativo de la actualización. Si la actualización automática está activada, las actualizaciones se iniciarán en el estado "scheduled". De lo contrario, las actualizaciones se iniciarán en el estado "proposed". Los valores definidos son:

* "no disponible" - La actualización no está disponible en este momento
* "propuesta" - La actualización está propuesta pero no se ejecutará automáticamente hasta que se apruebe
* "programada" - la actualización está aprobada pero no está lista para instalarse debido a dependencias, ventanas de tiempo o recursos disponibles
* "running" - La actualización está en curso
* "complete" - La actualización ha finalizado
* "failed" - La actualización no se ha completado




| stateDesired | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica el estado deseado para "state". Este campo solo se incluye cuando el usuario puede solicitar directamente un cambio en el estado del recurso. Los valores definidos son:

* "proposed" - La actualización no está aprobada y no debe realizarse
* "programada" - La actualización está aprobada y debe realizarse en el plazo especificado
* "en ejecución" - La actualización debe realizarse inmediatamente, independientemente de la ventana de tiempo




| stateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Verdadero  a| 
Matriz de objetos JSON que enumera detalles adicionales sobre el "estado" actual. Si no hay detalles disponibles, esta matriz estará vacía.

* Artículos mínimos: 0




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Se ajusta al esquema de metadatos de Astra Si no se especifica en la actualización, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-upgrade",
  "version": "1.1",
  "id": "aa9a8e88-c012-55b1-b514-7cd94dc79008",
  "componentName": "trident",
  "componentInstance": "https://<dns_name>/accounts/0b311ae7-d89a-4a11-a52c-1349ca090415/topology/v1/clouds/fdda3ff3-a46a-43a4-902e-444fde2baeba/storageBackends/72d19c3c-eb43-4bec-b23e-a228c900aded",
  "componentID": "72d19c3c-eb43-4bec-b23e-a228c900aded",
  "upgradeVersion": "21.07.1",
  "currentVersion": "21.04.1",
  "dependencies": [],
  "state": "scheduled",
  "stateDesired": "scheduled",
  "stateDetails": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Se ajusta al esquema de metadatos de Astra Si no se especifica en la actualización, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====