---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-subscriptions.html 
summary: Lista todas las suscripciones 
---
= Lista todas las suscripciones
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/subscriptions`#

Devuelve una matriz JSON de todos los recursos coincidentes de la colección. Si se especifican campos individuales en la solicitud, la matriz JSON de elementos contendrá los campos solicitados para cada recurso coincidente en el orden especificado.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| continuar |  | consulta | Falso  a| 
Indica el token desde el que reanudar el listado.

Ejemplos de URL: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

Ejemplos OpenAPI: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>



| cuente | cadena | consulta | Falso  a| 
Indica si se debe devolver el número total de recursos en el objeto de metadatos.

Ejemplos de URL: "count=true"

Ejemplos de OpenAPI: "true"



| filtro | cadena | consulta | Falso  a| 
Indica qué campos deben coincidir para devolver un recurso al listar una colección.

Los operadores admitidos son:

* eq - Igualdad
* lt/gt - Menor que/Mayor que
* lte/gte - Menor o igual que/Mayor o igual que


Ejemplo de URL: "filter=field%20eq%20%27value%27"

Ejemplos OpenAPI: "field eq 'value'"



| incluya | cadena | consulta | Falso  a| 
Indica qué campos deben devolverse al listar una colección.

Ejemplos de URL: "include=id", "include=id,name"

Ejemplos OpenAPI: "id"



| límite | cadena | consulta | Falso  a| 
Indica el número máximo de recursos a devolver al listar una colección.

Ejemplos de URL: "limit=2"

Ejemplos OpenAPI: "2"



| OrderBy | cadena | consulta | Falso  a| 
Indica el orden de clasificación de los recursos al listar una colección.

Ejemplos de URL: "orderBy=name", "orderBy=name%20desc"

Ejemplos OpenAPI: "name desc"



| omitir | cadena | consulta | Falso  a| 
Indica el número de recursos que deben omitirse al listar una colección.

Ejemplos de URL: "skip=1"

Ejemplos OpenAPI: "1"

|===


== Respuesta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| artículos | array[Cualquiera de: link:#subscription_1_2_get_response_body["subscription_1.2_get_response_body"], array[]] | Verdadero  a| 



| metadatos | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadero  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-subscriptions",
  "version": "1.2",
  "items": [
    {
      "type": "application/astra-subscription",
      "version": "1.1",
      "id": "d4c865c9-64a7-4661-ae4a-3307dffcd3da",
      "customerProfileID": "2157047189",
      "paymentProfileID": "E7CEB0A9F1BECA32A02493E1B31D5955",
      "paymentExpiry": "2022-02-01T00:00:00Z",
      "purchaseOrderNumber": "72384632",
      "marketplace": "netapp",
      "licenseSN": "278343",
      "terms": "trial",
      "status": "inactive",
      "appLimit": 0,
      "namespaceLimit": 10,
      "subscriptionPeriod": 90,
      "gracePeriod": 7,
      "reminderBeforePeriod": 30,
      "onboardStatus": "success",
      "costPerAppUnit": 0,
      "costPerNamespaceUnit": 0.005,
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-05-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-05-06T12:24:52.256624Z",
        "createdBy": "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa"
      }
    },
    {
      "type": "application/astra-subscription",
      "version": "1.1",
      "id": "4c43ed8b-078f-4fe3-b8c6-5d515f6382e6",
      "customerProfileID": "2157047189",
      "paymentProfileID": "E7CEB0A9F1BECA32A02493E1B31D5955",
      "paymentExpiry": "2022-05-01T00:00:00Z",
      "purchaseOrderNumber": "92374658",
      "marketplace": "netapp",
      "licenseSN": "374623",
      "terms": "paid",
      "status": "active",
      "appLimit": 0,
      "namespaceLimit": -1,
      "subscriptionPeriod": -1,
      "gracePeriod": -1,
      "reminderBeforePeriod": -1,
      "onboardStatus": "success",
      "costPerAppUnit": 0,
      "costPerNamespaceUnit": 0.005,
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidParams | matriz[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parámetros de consulta no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
subscription_1.2_get_response_body

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-subscription"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"
* "1,2"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| customerProfileID | cadena | Verdadero  a| 
Cadena JSON que contiene el ID del perfil del cliente de http://authorize.net["Authorize.net"], que fue invocado por la interfaz de usuario, no está configurado para el periodo de prueba. Devuelve una cadena vacía durante la operación de lectura, si no está configurado. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 63




| paymentProfileID | cadena | Falso  a| 
Cadena JSON que contiene el ID del perfil de pago de http://Authorize.net["Authorize.net"] que fue invocado por la interfaz de usuario, no establecido para el periodo de prueba. Devuelve una cadena vacía durante la operación de lectura si no se establece. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 63




| paymentExpiry | cadena | Falso  a| 
Cadena JSON que contiene una marca de tiempo que indica cuándo caduca el método de pago. Esto se obtiene de authorize.net(http://authorize.net[] y lo establece la interfaz de usuario. Los valores definidos son:

* Conforme al esquema de fecha y hora ISO-8601. Este campo no se devuelve para los periodos de prueba.




| purchaseOrderNumber | cadena | Falso  a| 
Cadena JSON que contiene el número de orden de compra para el método de pago. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 31




| mercado | cadena | Falso  a| 
Cadena JSON que indica el marketplace de una cuenta donde se registrarán los pagos. Valores definidos:

* "netapp"
* "azure"
* "aws"
* "gcp"




| licenciaSN | cadena | Falso  a| 
Cadena JSON que contiene el número de serie de la licencia para el método de pago. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 31




| términos | cadena | Verdadero  a| 
Cadena JSON que indica el nivel actual de la cuenta. Los valores definidos son:

* "prueba"
* "pagado"




| estado | cadena | Verdadero  a| 
Cadena JSON que indica el estado actual de la suscripción. Los valores definidos son:

* "activo"
* "inactivo"




| appLimit | número | Verdadero  a| 
Número JSON que indica el límite de aplicación para esta suscripción. Un valor de -1 indica que no hay límite.



| namespaceLimit | número | Verdadero  a| 
Número JSON que indica el límite de espacio de nombres para esta suscripción. Un valor de -1 indica que no hay límite.



| subscriptionPeriod | número | Verdadero  a| 
Número JSON que indica el periodo de suscripción. Un valor de -1 indica que no hay límite. Unidad: días



| gracePeriod | número | Verdadero  a| 
Número JSON que indica el periodo de gracia después de que caduque la suscripción de prueba o se cancele una suscripción de pago. Unidad: días



| reminderBeforePeriod | número | Verdadero  a| 
Número JSON que indica el número de días antes de que finalice la suscripción de prueba cuando comenzarán las notificaciones al cliente. El valor se expresa en días con un valor de -1 que indica que no es aplicable.



| onboardStatus | cadena | Verdadero  a| 
Cadena JSON que indica el estado actual de la incorporación del cliente. Los valores válidos son "no iniciado", "en curso", "correcto", "fallido". Los valores definidos son:

* "no iniciado"
* "en curso"
* "éxito"
* "fallido"




| costPerAppUnit | número | Verdadero  a| 
Número JSON que indica el coste por unidad de aplicación. Para una versión de prueba, el valor es 0. Unidad: dólares estadounidenses



| costPerNamespaceUnit | número | Verdadero  a| 
Número JSON que indica el coste por unidad de espacio de nombres. Para una versión de prueba, el valor es 0. Unidad: dólares estadounidenses



| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| continuar | cadena | Falso  a| 



| cuente | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
====