---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-core-v1-licenses.html 
summary: Crear una nueva licencia 
---
= Crear una nueva licencia
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/licenses`#

Indica los valores deseados para el recurso API de licencia que se va a crear.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}


|===


== Cuerpo de la solicitud

Indica los valores deseados para el recurso API de licencia que se va a crear.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-license"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"




| asignación | cadena | Falso  a| 
Cadena JSON que contiene un ID que indica a qué se asigna la licencia. Solo está presente cuando se asigna la licencia. Para las licencias de Astra Control Center, este campo debe rellenarse con el ID de cuenta y debe coincidir con el ID de cuenta especificado en el POST URI. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| deviceCredentialID | cadena | Falso  a| 
Cadena JSON que contiene el identificador de deviceCredential asociado con la API de credenciales. Solo está presente para las licencias de Astra Data Store. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| licenseText | cadena | Verdadero  a| 
Cadena JSON que contiene una representación codificada en base64 de la licencia JSON obtenida del sistema de licencias NetApp. Esto debe proporcionarse en el orden original a nivel de bytes para permitir la verificación de la firma. Los valores definidos son:

* Conforme al esquema de datos codificados en base64




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Falso  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de solicitud
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-license",
  "version": "1.0",
  "allocation": "4185d09b-6687-4801-a832-c005a9d94f41",
  "licenseText": "ewogICAic3RhdHVzUmVzcCI6ewogMTYwNzAwIgp9"
}
----
====


== Respuesta

[source]
----
Status: 201, Returns the newly created license resource in the JSON response body.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-license"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| asignación | cadena | Falso  a| 
Cadena JSON que contiene un ID que indica a qué se asigna la licencia. Solo está presente cuando se asigna la licencia. Para las licencias de Astra Control Center, este campo debe rellenarse con el ID de cuenta y debe coincidir con el ID de cuenta especificado en el POST URI. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| hostID | cadena | Falso  a| 
Cadena JSON que contiene un identificador de host al que está vinculada una licencia. Solo está presente si la licencia está bloqueada por host. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63




| deviceCredentialID | cadena | Falso  a| 
Cadena JSON que contiene el identificador de deviceCredential asociado con la API de credenciales. Solo está presente para las licencias de Astra Data Store. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| isEvaluation | cadena | Verdadero  a| 
Cadena JSON que indica si la licencia es una licencia de evaluación. Los valores definidos son:

* "true"
* "false"




| licenseProtocol | cadena | Verdadero  a| 
Cadena JSON que contiene el protocolo de licencia extraído de la licencia. Los valores definidos son:

* Contenido de cadena no validado por el esquema




| licenseText | cadena | Verdadero  a| 
Cadena JSON que contiene una representación codificada en base64 de la licencia JSON obtenida del sistema de licencias NetApp. Esto debe proporcionarse en el orden original a nivel de bytes para permitir la verificación de la firma. Los valores definidos son:

* Conforme al esquema de datos codificados en base64




| validFromTimestamp | cadena | Verdadero  a| 
Cadena JSON que contiene una marca de tiempo que indica cuándo la licencia se vuelve válida. Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| validUntilTimestamp | cadena | Verdadero  a| 
Cadena JSON que contiene una marca de tiempo que indica cuándo deja de ser válida la licencia. Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| producto | cadena | Verdadero  a| 
Cadena JSON que contiene la cadena del producto extraída de la licencia. Los valores definidos son:

* Contenido de cadena no validado por el esquema




| productVersion | cadena | Verdadero  a| 
Cadena JSON que contiene la cadena de versión extraída de la licencia. Los valores definidos son:

* Contenido de cadena no validado por el esquema




| productSN | cadena | Verdadero  a| 
Cadena JSON que contiene el número de serie extraído de la licencia. Los valores definidos son:

* Contenido de cadena no validado por el esquema




| características | cadena | Verdadero  a| 
Cadena JSON que contiene el valor del paquete extraído de la licencia. Los valores definidos son:

* Contenido de cadena no validado por el esquema




| capacidad | cadena | Verdadero  a| 
Cadena JSON que contiene la capacidad extraída de la licencia.



| capacity2 | cadena | Verdadero  a| 
Cadena JSON que contiene la capacidad secundaria extraída de la licencia.



| complementos | array[link:#addons["complementos"]] | Falso  a| 
Matriz de objetos JSON que contiene la lista de add-ons de la licencia. Un add-on es un cambio en la licencia que se produce en una posible fecha futura.



| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-license",
  "version": "1.0",
  "id": "6db53b32-8417-5d3c-8ef0-552fc602c78f",
  "allocation": "4185d09b-6687-4801-a832-c005a9d94f41",
  "hostID": "99132549-e0c2-4203-9d1e-598628b4ff9b",
  "isEvaluation": "false",
  "licenseProtocol": "ASTRASDS-ENT-SUBS",
  "licenseText": "ewogICAic3RhdHVzUmVzcCI6ewogMTYwNzAwIgp9",
  "validFromTimestamp": "2020-08-06T00:00:00.000000Z",
  "validUntilTimestamp": "2021-08-06T00:00:00.000000Z",
  "product": "Astra Control Center",
  "productVersion": "1.0",
  "productSN": "320000046",
  "features": "ASTRA-ENT-STD",
  "capacity": "4000",
  "capacity2": "0",
  "addons": [
    {
      "startDate": "2020-08-06T00:00:00.000000Z",
      "endDate": "2021-08-06T00:00:00.000000Z",
      "capacity": "4000",
      "licenseProtocol": "ASTRA-ENT-STD",
      "features": "p-nfs,dm-storage-policy-based-pvs-for-k8s,dm-spbm-based-vvols-for-vms,dm-storage-efficiency,dm-data-at-rest-encryption"
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
complementos

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| startDate | cadena | Falso  a| 
Cadena JSON que contiene una marca de tiempo que indica cuándo este complemento se vuelve válido. Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| endDate | cadena | Falso  a| 
Cadena JSON que contiene una marca de tiempo que indica cuándo deja de ser válido este complemento. Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| características | cadena | Falso  a| 
Cadena JSON que contiene la lista de características asociadas a este complemento. Los valores definidos son:

* Contenido de cadena no validado por el esquema.




| capacidad | cadena | Falso  a| 
Cadena JSON que contiene la capacidad extraída del complemento. Los valores definidos son:

* Contenido de cadena no validado por el esquema




| licenseProtocol | cadena | Falso  a| 
Cadena JSON que contiene el protocolo de licencia asociado a este complemento. Los valores definidos son:

* Contenido de cadena no validado por el esquema


|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del campo no válido del cuerpo de la solicitud



| motivo | cadena | Verdadero  a| 
Motivo por el que el campo del cuerpo de la solicitud no es válido

|===
====