---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-topology-v1-clouds.html 
summary: Crear una nueva nube 
---
= Crear una nueva nube
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clouds`#

Indica los valores deseados para el recurso Cloud API que se va a crear.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}


|===


== Cuerpo de la solicitud

Indica los valores deseados para el recurso Cloud API que se va a crear.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-cloud"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| nombre | cadena | Verdadero  a| 
Cadena JSON que contiene el nombre de la nube. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63
* Esta cadena se valida internamente para evitar ataques XSS, Unicode, de traspaso de directorios y de inyección SQL




| cloudType | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica el tipo de nube. Los valores definidos son:

* "gcp" - La nube es proporcionada por Google
* "azure" - La nube es proporcionada por Microsoft
* "aws" - La nube es proporcionada por Amazon
* "privada" - La nube está gestionada por el cliente




| credentialID | cadena | Falso  a| 
Cadena JSON que contiene un valor que indica el ID de la credencial que contiene la cuenta de servicio para la nube. Esto es necesario para cloudType "gcp", "azure" y "aws". Los valores definidos son:

* Cumple con el esquema del identificador Astra




| defaultBucketID | cadena | Falso  a| 
Cadena JSON que contiene el ID de un bucket que debe utilizarse por defecto al crear copias de seguridad para aplicaciones dentro de la nube. Es necesario al clonar aplicaciones entre clústeres y se utiliza por defecto si no se especifica un bucket al crear copias de seguridad y programaciones. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Falso  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de solicitud
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-cloud",
  "version": "1.1",
  "name": "GKE",
  "cloudType": "gcp",
  "credentialID": "6fa2f917-f730-41b8-9c15-17f531843b31"
}
----
====


== Respuesta

[source]
----
Status: 201, Returns the newly created cloud resource in the JSON response body.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-cloud"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| nombre | cadena | Verdadero  a| 
Cadena JSON que contiene el nombre de la nube. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63
* Esta cadena se valida internamente para evitar ataques XSS, Unicode, de traspaso de directorios y de inyección SQL




| estado | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica el estado operativo de la nube. Los valores definidos son:

* "pendiente" - La nube está programada para ser descubierta
* "descubriendo" - La nube está en proceso de ser descubierta
* "provisioning" - La nube está en proceso de aprovisionamiento
* "running" - La nube funciona con normalidad
* "failed" - La nube se encuentra en un estado de fallo permanente
* "removed" - La nube no es accesible actualmente
* "desconocido" - No se puede determinar el estado de la nube




| stateUnready | array[string] | Verdadero  a| 
Matriz JSON de cadenas JSON, cada una de las cuales indica un motivo por el que una nube no puede realizar la transición a "en ejecución" o por el que ha realizado la transición a "fallida". Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 127




| cloudType | cadena | Verdadero  a| 
Cadena JSON que contiene un valor que indica el tipo de nube. Los valores definidos son:

* "gcp" - La nube es proporcionada por Google
* "azure" - La nube es proporcionada por Microsoft
* "aws" - La nube es proporcionada por Amazon
* "privada" - La nube está gestionada por el cliente




| credentialID | cadena | Falso  a| 
Cadena JSON que contiene un valor que indica el ID de la credencial que contiene la cuenta de servicio para la nube. Esto es necesario para cloudType "gcp", "azure" y "aws". Los valores definidos son:

* Cumple con el esquema del identificador Astra




| defaultBucketID | cadena | Falso  a| 
Cadena JSON que contiene el ID de un bucket que debe utilizarse por defecto al crear copias de seguridad para aplicaciones dentro de la nube. Es necesario al clonar aplicaciones entre clústeres y se utiliza por defecto si no se especifica un bucket al crear copias de seguridad y programaciones. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-cloud",
  "version": "1.1",
  "id": "1c9512c3-ec62-5ed8-8013-02fc090b9d03",
  "name": "GKE",
  "state": "discovering",
  "stateUnready": [
    "Cloud discovery in progress"
  ],
  "cloudType": "gcp",
  "credentialID": "6fa2f917-f730-41b8-9c15-17f531843b31",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del campo no válido del cuerpo de la solicitud



| motivo | cadena | Verdadero  a| 
Motivo por el que el campo del cuerpo de la solicitud no es válido

|===
====