---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-k8s-v1-apps-executionhooks.html 
summary: Crear un nuevo gancho de ejecución para una app 
---
= Crear un nuevo gancho de ejecución para una app
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHooks`#

Indica los valores deseados para el recurso Execution Hook API que se va a crear.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| app_id | cadena | ruta | Verdadero  a| 
ID del recurso que contiene la aplicación

|===


== Cuerpo de la solicitud

Indica los valores deseados para el recurso Execution Hook API que se va a crear.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-executionHook"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| nombre | cadena | Verdadero  a| 
Cadena JSON que contiene un nombre especificado por el usuario para el recurso. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63 El nombre debe ser único en todos los recursos de ejecución hook.




| hookType | cadena | Verdadero  a| 
Cadena JSON que define el tipo de gancho. Los valores definidos son:

* "netapp" - NetApp proporcionó el gancho de ejecución.
* "custom" - Vinculado a un ID de aplicación específico. Los recursos de gancho de ejecución con hookType "netapp" son de solo lectura.




| matchingCriteria | array[link:#matchingCriteria["matchingCriteria"]] | Falso  a| 
Matriz JSON de objetos JSON que describen los criterios de coincidencia para el gancho de ejecución. Cuando se especifican múltiples matchingCriteria se aplica un AND lógico a los criterios. Los valores definidos son:

* Elementos mínimos: 0
* Máximo de elementos: 10




| acción | cadena | Verdadero  a| 
Cadena JSON que indica qué acción ejecutará el gancho de ejecución si se cumplen los criterios de coincidencia. Los valores definidos son:

* "instantánea"
* "copia de seguridad"
* "restaurar"
* "failover"




| escenario | cadena | Verdadero  a| 
Cadena JSON que indica la etapa durante la acción en la que se ejecutará el gancho. Los valores definidos son:

* "pre" - El gancho de ejecución se ejecutará antes de la acción especificada.
* "post" - El gancho de ejecución se ejecutará después de la acción especificada. Los valores para la acción "snapshot" son "pre" y "post". Los valores para la acción "backup" son "pre" y "post". El valor para la acción "restore" es "post". El valor para la acción "failover" es "post".




| hookSourceID | cadena | Verdadero  a| 
Cadena JSON que contiene el ID de la fuente del hook que se ejecuta a través de este hook de ejecución. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| argumentos | array[string] | Falso  a| 
Matriz JSON de cadenas JSON para los argumentos de la fuente. Los valores definidos son:

* Elementos mínimos: 0
* Máximo de elementos: 16
* Longitud mínima: 0
* Longitud máxima: 127




| appID | cadena | Verdadero  a| 
Cadena JSON que contiene el ID asociado de la aplicación a la que está vinculado este hook. En esencia, otros criterios de coincidencia, si se establecen. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| habilitado | cadena | Falso  a| 
Cadena JSON que indica si el gancho de ejecución está habilitado. Los valores definidos son:

* "true" - El gancho de ejecución está habilitado y se ejecutará según lo especificado.
* "false" - El gancho de ejecución está desactivado y nunca se ejecutará. El valor por defecto es "true".




| descripción | cadena | Falso  a| 
Cadena JSON que contiene una descripción especificada por el usuario para la fuente del gancho. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 511




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Falso  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de solicitud
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "name": "Payroll",
  "hookType": "custom",
  "action": "snapshot",
  "stage": "pre",
  "hookSourceID": "50e89023-ba84-435d-bb47-1833f4c250ff",
  "arguments": [
    "freeze"
  ],
  "appID": "7be5ae7c-151d-4230-ac39-ac1d0b33c2a9",
  "enabled": "true",
  "description": "Payroll production hook"
}
----
====


== Respuesta

[source]
----
Status: 201, Returns the newly created executionHook resource in the JSON response body.
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-executionHook"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | cadena | Verdadero  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| nombre | cadena | Verdadero  a| 
Cadena JSON que contiene un nombre especificado por el usuario para el recurso. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63 El nombre debe ser único en todos los recursos de ejecución hook.




| hookType | cadena | Verdadero  a| 
Cadena JSON que define el tipo de gancho. Los valores definidos son:

* "netapp" - NetApp proporcionó el gancho de ejecución.
* "custom" - Vinculado a un ID de aplicación específico. Los recursos de gancho de ejecución con hookType "netapp" son de solo lectura.




| matchingCriteria | array[link:#matchingCriteria["matchingCriteria"]] | Verdadero  a| 
Matriz JSON de objetos JSON que describen los criterios de coincidencia para el gancho de ejecución. Cuando se especifican múltiples matchingCriteria se aplica un AND lógico a los criterios. Los valores definidos son:

* Elementos mínimos: 0
* Máximo de elementos: 10




| matchingContainers | array[link:#matchingContainers["matchingContainers"]] | Falso  a| 
Matriz JSON de objetos JSON de cada contenedor que coincida con los criterios de coincidencia configurados dentro de la app definida.



| matchingImages | array[string] | Falso  a| 
Matriz JSON de cadenas JSON para las imágenes de contenedor coincidentes. Los valores definidos son:

* Elementos mínimos: 0
* Máximo de elementos: 4095
* Longitud mínima: 1
* Longitud máxima: 255




| acción | cadena | Verdadero  a| 
Cadena JSON que indica qué acción ejecutará el gancho de ejecución si se cumplen los criterios de coincidencia. Los valores definidos son:

* "instantánea"
* "copia de seguridad"
* "restaurar"
* "failover"




| escenario | cadena | Verdadero  a| 
Cadena JSON que indica la etapa durante la acción en la que se ejecutará el gancho. Los valores definidos son:

* "pre" - El gancho de ejecución se ejecutará antes de la acción especificada.
* "post" - El gancho de ejecución se ejecutará después de la acción especificada. Los valores para la acción "snapshot" son "pre" y "post". Los valores para la acción "backup" son "pre" y "post". El valor para la acción "restore" es "post". El valor para la acción "failover" es "post".




| hookSourceID | cadena | Verdadero  a| 
Cadena JSON que contiene el ID de la fuente del hook que se ejecuta a través de este hook de ejecución. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| argumentos | array[string] | Falso  a| 
Matriz JSON de cadenas JSON para los argumentos de la fuente. Los valores definidos son:

* Elementos mínimos: 0
* Máximo de elementos: 16
* Longitud mínima: 0
* Longitud máxima: 127




| appID | cadena | Falso  a| 
Cadena JSON que contiene el ID asociado de la aplicación a la que está vinculado este hook. En esencia, otros criterios de coincidencia, si se establecen. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| habilitado | cadena | Verdadero  a| 
Cadena JSON que indica si el gancho de ejecución está habilitado. Los valores definidos son:

* "true" - El gancho de ejecución está habilitado y se ejecutará según lo especificado.
* "false" - El gancho de ejecución está desactivado y nunca se ejecutará. El valor por defecto es "true".




| descripción | cadena | Falso  a| 
Cadena JSON que contiene una descripción especificada por el usuario para la fuente del gancho. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 511




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Verdadero  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "id": "5f7e2e31-280d-5984-a28b-2d19ab5b77c0",
  "name": "Payroll",
  "hookType": "custom",
  "matchingCriteria": [],
  "action": "snapshot",
  "stage": "pre",
  "hookSourceID": "50e89023-ba84-435d-bb47-1833f4c250ff",
  "arguments": [
    "freeze"
  ],
  "appID": "7be5ae7c-151d-4230-ac39-ac1d0b33c2a9",
  "enabled": "true",
  "description": "Payroll production hook",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
matchingCriteria

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Falso  a| 
Cadena JSON que identifica el tipo de criterio de coincidencia.



| valor | cadena | Falso  a| 
Cadena JSON que contiene una expresión regular para el tipo de coincidencia dado. Sintaxis de la expresión regular: https://github.com/google/re2/wiki/Syntax[]

|===
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
matchingCriteria

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Cadena JSON que identifica el tipo de criterio de coincidencia.



| valor | cadena | Verdadero  a| 
Cadena JSON que contiene una expresión regular para el tipo de coincidencia dado. Sintaxis de la expresión regular: https://github.com/google/re2/wiki/Syntax[]

|===
[role="api-collapsible-fifth-title"]
type_k8s_label

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
matchingContainers

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| podName | cadena | Falso  a| 
Cadena JSON del nombre del pod del contenedor coincidente.



| podLabels | array[link:#type_k8s_label["type_k8s_label"]] | Falso  a| 
Matriz JSON de objetos de etiquetas de las etiquetas del pod del contenedor coincidente.



| containerImage | cadena | Falso  a| 
Cadena JSON de la imagen del contenedor coincidente.



| containerName | cadena | Falso  a| 
Cadena JSON del nombre del contenedor coincidente.



| namespaceName | cadena | Falso  a| 
Cadena JSON del nombre del espacio de nombres del pod del contenedor coincidente.

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del campo no válido del cuerpo de la solicitud



| motivo | cadena | Verdadero  a| 
Motivo por el que el campo del cuerpo de la solicitud no es válido

|===
====