---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-settings-.html 
summary: Modificar un ajuste 
---
= Modificar un ajuste
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/settings/{setting_id}`#

Sustituye todo el recurso almacenado por el cuerpo de la solicitud JSON suministrado, conservando los valores clave que no son modificables por el usuario.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| setting_id | cadena | ruta | Verdadero  a| 
ID de la colección de ajustes a listar

|===


== Cuerpo de la solicitud

Sustituye todo el recurso almacenado por el cuerpo de la solicitud JSON suministrado, conservando los valores clave que no son modificables por el usuario.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-setting"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Falso  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| nombre | cadena | Falso  a| 
Cadena JSON que contiene un nombre para el ajuste, en notación jerárquica de puntos (.). Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63
* Esta cadena es validada internamente para prevenir ataques XSS, Unicode, directory traversal y SQL-injection. Este valor es especificado por el configmap que es cargado en tiempo de ejecución y no puede ser actualizado por el usuario.




| currentConfig | link:#type_json["tipo_json"] | Falso  a| 
Objeto JSON que contiene las claves y valores que componen la configuración actual para este ajuste. El contenido de este objeto debe ajustarse al esquema JSON contenido en el campo configSchema. Los valores por defecto son suministrados por el configmap. Después de que los valores por defecto sean modificados por el usuario, no serán sobrescritos.



| desiredConfig | link:#type_json["tipo_json"] | Falso  a| 
Objeto JSON que contiene claves y valores que conforman la configuración solicitada para esta configuración. El contenido de este objeto debe ajustarse al esquema JSON contenido en el campo configSchema. El objeto no existe hasta que se especifica. Cuando se especifica, esto hace que el servicio de características notifique al servicio correspondiente para solicitar que se pueda aplicar la configuración deseada. El servicio correspondiente puede entonces realizar la validación y aplicar la configuración deseada a la configuración actual.



| configSchema | link:#type_json_schema["type_json_schema"] | Falso  a| 
Objeto JSON que contiene el esquema JSON para la propiedad config en este recurso. Debe ajustarse a JSON Schema Draft 7. Si los valores config están presentes en el recurso, la validación contra el configSchema indicado es obligatoria. Como convención común, se recomienda que las configuraciones tengan un campo "isEnabled", cuando sea apropiado. El campo "isEnabled" contiene un valor que indica si la configuración está activada ("true") o desactivada ("false").



| estado | cadena | Falso  a| 
Cadena JSON que contiene un valor que indica el estado operativo de la aplicación. Los valores definidos son:

* "válido" - La configuración actual coincide con la configuración deseada.
* "pendiente" - Se está aplicando la configuración deseada.
* "error" - No se puede aplicar la configuración deseada.




| stateUnready | array[string] | Falso  a| 
Matriz JSON de cadenas JSON, cada una de las cuales indica un motivo por el que la configuración no se ha aplicado correctamente. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 127




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Falso  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Se ajusta al esquema de metadatos de Astra Si no se especifica en la actualización, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de solicitud
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-setting",
  "version": "1.1",
  "desiredConfig": {
    "credential": "e3d2ea77-398e-49be-85fd-ec66d9426a06",
    "port": 587,
    "relayServer": "link:http://smtp.sendgrid.net[smtp.sendgrid.net]",
    "isEnabled": "true"
  }
}
----
====


== Respuesta

[source]
----
Status: 204, Indicates if the setting resource was updated.
----


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Respuesta

[source]
----
Status: 503, Service unavailable
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/41",
  "title": "Service not ready",
  "detail": "Currently, the service can't respond to this request.",
  "status": "503"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
tipo_json

Objeto JSON que contiene las claves y valores que componen la configuración actual para este ajuste. El contenido de este objeto debe ajustarse al esquema JSON contenido en el campo configSchema. Los valores por defecto son suministrados por el configmap. Después de que los valores por defecto sean modificados por el usuario, no serán sobrescritos.

[role="api-collapsible-fifth-title"]
tipo_json

Objeto JSON que contiene claves y valores que conforman la configuración solicitada para esta configuración. El contenido de este objeto debe ajustarse al esquema JSON contenido en el campo configSchema. El objeto no existe hasta que se especifica. Cuando se especifica, esto hace que el servicio de características notifique al servicio correspondiente para solicitar que se pueda aplicar la configuración deseada. El servicio correspondiente puede entonces realizar la validación y aplicar la configuración deseada a la configuración actual.

[role="api-collapsible-fifth-title"]
propiedades

[role="api-collapsible-fifth-title"]
type_json_schema

Objeto JSON que contiene el esquema JSON para la propiedad config en este recurso. Debe ajustarse a JSON Schema Draft 7. Si los valores config están presentes en el recurso, la validación contra el configSchema indicado es obligatoria. Como convención común, se recomienda que las configuraciones tengan un campo "isEnabled", cuando sea apropiado. El campo "isEnabled" contiene un valor que indica si la configuración está activada ("true") o desactivada ("false").

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| $schema | cadena | Verdadero  a| 



| tipo | cadena | Verdadero  a| 



| propiedades | link:#properties["propiedades"] | Verdadero  a| 



| additionalProperties | booleano | Verdadero  a| 



| obligatorio | array[string] | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Se ajusta al esquema de metadatos de Astra Si no se especifica en la actualización, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del campo no válido del cuerpo de la solicitud



| motivo | cadena | Verdadero  a| 
Motivo por el que el campo del cuerpo de la solicitud no es válido

|===
====