---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-topology-v1-buckets-.html 
summary: Modificar un bucket 
---
= Modificar un bucket
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/buckets/{bucket_id}`#

Sustituye todo el recurso almacenado por el cuerpo de la solicitud JSON suministrado, conservando los valores clave que no son modificables por el usuario.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| bucket_id | cadena | ruta | Verdadero  a| 
ID de la colección de cubos a listar

|===


== Cuerpo de la solicitud

Sustituye todo el recurso almacenado por el cuerpo de la solicitud JSON suministrado, conservando los valores clave que no son modificables por el usuario.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-bucket"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"
* "1,2"




| id | cadena | Falso  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| nombre | cadena | Falso  a| 
Cadena JSON que contiene un nombre asignado por el usuario para el bucket. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 256




| credentialID | cadena | Falso  a| 
Cadena JSON que contiene el identificador de las credenciales utilizadas para acceder al bucket. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| estado | cadena | Falso  a| 
Cadena JSON que contiene un valor que indica el estado operativo del bucket. Los valores definidos son:

* "pendiente" - El bucket está programado para ser descubierto
* "available" - El cubo está disponible para su uso
* "failed" - El bucket está en estado de fallo permanente
* "eliminado" - El bucket no está accesible actualmente
* "desconocido" - No se puede determinar el estado del bucket




| stateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falso  a| 
Matriz JSON de objetos JSON que enumera detalles adicionales sobre por qué "state" pasó a "removed" o "failed". Si no hay detalles disponibles, esta matriz estará vacía.

* Elementos mínimos: 0




| proveedor | cadena | Falso  a| 
Cadena JSON que indica el protocolo del bucket que puede utilizarse para acceder al bucket. Los valores definidos son:

* "ontap-s3"
* "storagegrid-s3"
* "generic-s3"
* "gcp"
* "azure"
* "aws"




| bucketParameters | link:#bucketParameters["bucketParameters"] | Falso  a| 
Objeto JSON que proporciona información específica del proveedor del bucket necesaria para acceder al bucket. Los valores específicos de este bucket varían según el proveedor.



| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Falso  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de solicitud
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-bucket",
  "version": "1.2",
  "name": "New Bucket Name"
}
----
====


== Respuesta

[source]
----
Status: 204, Indicates if the bucket resource was updated.
----


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
s3

Objeto JSON que proporciona parámetros de protocolo de Simple Storage Service (S3). (Usa este objeto para todos los proveedores de tipo S3).

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| serverURL | cadena | Falso  a| 
Cadena JSON que contiene una URL a la ruta base para el bucket. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 1023




| bucketName | cadena | Falso  a| 
Cadena JSON que contiene el nombre del bucket S3. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 63


|===
[role="api-collapsible-fifth-title"]
gcp

Objeto JSON que proporciona los parámetros del protocolo de Google Cloud.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| bucketName | cadena | Falso  a| 
Cadena JSON que contiene el nombre del bucket de Google Cloud de respaldo. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 63


|===
[role="api-collapsible-fifth-title"]
azure

Objeto JSON que proporciona los parámetros del protocolo Azure.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| storageAccount | cadena | Falso  a| 
Cadena JSON que contiene el nombre de la cuenta de almacenamiento Azure. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 63




| bucketName | cadena | Falso  a| 
Cadena JSON que contiene el nombre del blob Azure de respaldo. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 63


|===
[role="api-collapsible-fifth-title"]
bucketParameters

Objeto JSON que proporciona información específica del proveedor del bucket necesaria para acceder al bucket. Los valores específicos de este bucket varían según el proveedor.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| s3 | link:#s3["s3"] | Falso  a| 
Objeto JSON que proporciona parámetros de protocolo de Simple Storage Service (S3). (Usa este objeto para todos los proveedores de tipo S3).



| gcp | link:#gcp["gcp"] | Falso  a| 
Objeto JSON que proporciona los parámetros del protocolo de Google Cloud.



| azure | link:#azure["azure"] | Falso  a| 
Objeto JSON que proporciona los parámetros del protocolo Azure.

|===
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del campo no válido del cuerpo de la solicitud



| motivo | cadena | Verdadero  a| 
Motivo por el que el campo del cuerpo de la solicitud no es válido

|===
====