---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-upgrades-.html 
summary: Modificar una actualización 
---
= Modificar una actualización
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/upgrades/{upgrade_id}`#

Sustituye todo el recurso almacenado por el cuerpo de la solicitud JSON suministrado, conservando los valores clave que no son modificables por el usuario.

*Efectos secundarios*

* Las actualizaciones se programan o ejecutan en función del estado deseado.




== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| upgrade_id | cadena | ruta | Verdadero  a| 
ID de la colección de actualizaciones a listar

|===


== Cuerpo de la solicitud

Sustituye todo el recurso almacenado por el cuerpo de la solicitud JSON suministrado, conservando los valores clave que no son modificables por el usuario.

*Efectos secundarios*

* Las actualizaciones se programan o ejecutan en función del estado deseado.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-upgrade"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Falso  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| componentName | cadena | Falso  a| 
Cadena JSON que contiene el nombre del tipo de software que puede actualizarse. Los valores definidos son:

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| componentInstance | cadena | Falso  a| 
Cadena JSON que contiene el URI del componente que puede actualizarse. Los valores definidos son:

* Longitud mínima: 3
* Longitud máxima: 4095




| componentID | cadena | Falso  a| 
Cadena JSON que contiene un identificador único global del componente que puede actualizarse. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| upgradeVersion | cadena | Falso  a| 
Cadena JSON que contiene el SemVer del archivo de imagen de software al que se puede actualizar. Los valores definidos son:

* Cumple con el esquema SemVer




| currentVersion | cadena | Falso  a| 
Cadena JSON que contiene el SemVer actual de la entidad que se va a actualizar. Los valores definidos son:

* Cumple con el esquema SemVer




| dependencias | array[string] | Falso  a| 
Matriz JSON de cadenas JSON, cada una de las cuales contiene el UUID de una actualización que debe completarse antes de que esta actualización pueda continuar. Se utiliza para determinar qué actualizaciones se realizarán como requisitos previos y en qué orden. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| estado | cadena | Falso  a| 
Cadena JSON que contiene un valor que indica el estado operativo de la actualización. Si la actualización automática está activada, las actualizaciones se iniciarán en el estado "scheduled". De lo contrario, las actualizaciones se iniciarán en el estado "proposed". Los valores definidos son:

* "no disponible" - La actualización no está disponible en este momento
* "propuesta" - La actualización está propuesta pero no se ejecutará automáticamente hasta que se apruebe
* "programada" - la actualización está aprobada pero no está lista para instalarse debido a dependencias, ventanas de tiempo o recursos disponibles
* "running" - La actualización está en curso
* "complete" - La actualización ha finalizado
* "failed" - La actualización no se ha completado




| stateDesired | cadena | Falso  a| 
Cadena JSON que contiene un valor que indica el estado deseado para "state". Este campo solo se incluye cuando el usuario puede solicitar directamente un cambio en el estado del recurso. Los valores definidos son:

* "proposed" - La actualización no está aprobada y no debe realizarse
* "programada" - La actualización está aprobada y debe realizarse en el plazo especificado
* "en ejecución" - La actualización debe realizarse inmediatamente, independientemente de la ventana de tiempo




| stateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falso  a| 
Matriz de objetos JSON que enumera detalles adicionales sobre el "estado" actual. Si no hay detalles disponibles, esta matriz estará vacía.

* Artículos mínimos: 0




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Falso  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Se ajusta al esquema de metadatos de Astra Si no se especifica en la actualización, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de solicitud
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-upgrade",
  "version": "1.1",
  "stateDesired": "running"
}
----
====


== Respuesta

[source]
----
Status: 204, Indicates if the upgrade resource was updated.
----


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Se ajusta al esquema de metadatos de Astra Si no se especifica en la actualización, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del campo no válido del cuerpo de la solicitud



| motivo | cadena | Verdadero  a| 
Motivo por el que el campo del cuerpo de la solicitud no es válido

|===
====