---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-users-.html 
summary: Modificar un usuario 
---
= Modificar un usuario
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/users/{user_id}`#

Sustituye todo el recurso almacenado por el cuerpo de la solicitud JSON suministrado, conservando los valores clave que no son modificables por el usuario.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| user_id | cadena | ruta | Verdadero  a| 
ID de la colección de usuarios a listar

|===


== Cuerpo de la solicitud

Sustituye todo el recurso almacenado por el cuerpo de la solicitud JSON suministrado, conservando los valores clave que no son modificables por el usuario.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-user"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"
* "1,2"




| id | cadena | Falso  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| estado | cadena | Falso  a| 
Cadena JSON que contiene un valor que indica el estado operativo del usuario. Los valores definidos son:

* "pending" - La cuenta de usuario está en proceso de creación. El usuario solo puede leer y modificar el recurso de usuario (valor por defecto).
* Este estado no es válido para un usuario con "authProvider" como "local"
* "active" - La cuenta de usuario está operativa (el usuario puede iniciar sesión si la configuración de la cuenta "isEnabled" es "true").
* Este es el valor por defecto para un usuario con "authProvider" como "local"
* "suspended" - La cuenta de usuario está suspendida (el usuario no puede iniciar sesión independientemente de la configuración de la cuenta "isEnabled").




| isEnabled | cadena | Falso  a| 
Cadena JSON que indica si el usuario tiene permiso para iniciar sesión. Los valores definidos son:

* "true" - El usuario puede iniciar sesión; valor por defecto al crear.
* "false" - El usuario no puede iniciar sesión.




| authID | cadena | Falso  a| 
Cadena JSON que contiene el identificador asociado a un proveedor de identidad externo. El contenido de esta cadena depende del authProvider especificado. Para un usuario con "authProvider" como "local", "authID" se establece con el valor de "email". Para un usuario con "authProvider" como "ldap", "authID" se establece con su Nombre Distinguido (DN) del servidor LDAP.



| authProvider | cadena | Falso  a| 
Cadena JSON que indica el contexto del identificador idAuth. Los valores definidos son:

* "cloud-central" - La autenticación de usuario procede del servicio NetApp Cloud Central
* "local" - La autenticación de usuario procede del almacén local de usuarios/contraseñas
* "ldap" - La autenticación de usuario proviene de un servidor LDAP externo En Astra Control Center, se requiere que todos los usuarios tengan un valor de "local" o "ldap". Si no se especifica un valor, se elegirá por defecto el valor "local". En Astra Control Service, no se admite "authProvider" como "local" o "ldap". Si no se especifica un valor, se elegirá por defecto "cloud-central".




| firstName | cadena | Falso  a| 
Cadena JSON que contiene un nombre de pila largo especificado por el usuario. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 63
* Esta cadena se valida internamente para evitar ataques XSS, Unicode, de traspaso de directorios y de inyección SQL




| lastName | cadena | Falso  a| 
Cadena JSON que contiene un apellido largo especificado por el usuario. Los valores definidos son:

* Longitud mínima: 0
* Longitud máxima: 63
* Esta cadena se valida internamente para evitar ataques XSS, Unicode, de traspaso de directorios y de inyección SQL




| companyName | cadena | Falso  a| 
Cadena JSON que contiene el nombre de la empresa asociada al usuario. Si esta clave no existe, indica que no se ha proporcionado un nombre de empresa. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63
* Esta cadena se valida internamente para evitar ataques XSS, Unicode, de traspaso de directorios y de inyección SQL




| correo electrónico | cadena | Falso  a| 
Cadenas JSON que contienen una dirección de correo electrónico especificada por el usuario.



| teléfono | cadena | Falso  a| 
Cadena JSON que contiene el número de teléfono del usuario. Si esta clave no existe, indica que no se ha proporcionado un número de teléfono.



| postalAddress | link:#postalAddress["postalAddress"] | Falso  a| 
Objeto JSON que contiene una colección de campos que especifica una dirección. Si esta clave no existe, indica que no se ha proporcionado una dirección. Si esta clave existe, los seis campos contenidos estarán presentes. Si el usuario no ha proporcionado nada, la cadena estará vacía.



| sendWelcomeEmail | cadena | Falso  a| 
Cadena JSON que indica si se enviará un correo electrónico de bienvenida tras la validación. Si no se especifica al crear, el valor se establecerá en "true" para ACS y en "false" para Astra Control Center. Los valores definidos son:

* "true" - Se enviará un correo electrónico de bienvenida; valor por defecto al crear
* "false" - No se enviará un correo electrónico de bienvenida Para un usuario con "authProvider" como "local" o "ldap", este valor se ignora y se establece en "false".




| enableTimestamp | cadena | Falso  a| 
Cadena JSON que contiene una marca de tiempo con formato ISO-8601 que indica cuándo se habilitó el usuario por última vez. Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| lastActTimestamp | cadena | Falso  a| 
Cadena JSON que contiene una marca de tiempo con formato ISO-8601 que indica cuándo se invocó por última vez la API de identidad en nombre de este usuario. (Nota: esto es caro.) Los valores definidos son:

* Cumple con el esquema de fecha y hora ISO-8601




| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Falso  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de solicitud
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-user",
  "version": "1.2",
  "firstName": "John",
  "lastName": "Dale",
  "email": "jdale@example.com"
}
----
====


== Respuesta

[source]
----
Status: 204, Indicates if the user resource was updated.
----


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
postalAddress

Objeto JSON que contiene una colección de campos que especifica una dirección. Si esta clave no existe, indica que no se ha proporcionado una dirección. Si esta clave existe, los seis campos contenidos estarán presentes. Si el usuario no ha proporcionado nada, la cadena estará vacía.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| addressCountry | cadena | Verdadero  a| 
Cadena JSON que contiene el nombre del país o el código de país asociado a la dirección postal, tal como se especifica en ISO 3166 Alpha-2. Los valores definidos son:

* Longitud mínima: 2
* Longitud máxima: 2




| addressLocality | cadena | Verdadero  a| 
Cadena JSON que contiene la localidad (por ejemplo, ciudad) asociada a la dirección postal. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63




| addressRegion | cadena | Verdadero  a| 
Cadena JSON que contiene la región (por ejemplo, estado) asociada a la dirección postal. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63




| postalCode | cadena | Verdadero  a| 
Cadena JSON que contiene el código postal asociado a la dirección postal. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63




| streetAddress1 | cadena | Verdadero  a| 
Cadena JSON que contiene la dirección de la calle asociada a la dirección postal. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63




| streetAddress2 | cadena | Falso  a| 
Cadena JSON que contiene información auxiliar opcional sobre la dirección, apartado de correos, etc. Los valores definidos son:

* Longitud mínima: 1
* Longitud máxima: 63


|===
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del campo no válido del cuerpo de la solicitud



| motivo | cadena | Verdadero  a| 
Motivo por el que el campo del cuerpo de la solicitud no es válido

|===
====