---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/put-accounts-core-v1-users-groups-rolebindings-.html 
summary: Modificar un enlace de rol para un grupo asociado a un usuario 
---
= Modificar un enlace de rol para un grupo asociado a un usuario
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/users/{user_id}/groups/{group_id}/roleBindings/{roleBinding_id}`#

Sustituye todo el recurso almacenado por el cuerpo de la solicitud JSON suministrado, conservando los valores clave que no son modificables por el usuario.



== Parámetros

[cols="5*"]
|===
| Nombre | Tipo | En | Obligatorio | Descripción 


| account_id | cadena | ruta | Verdadero  a| 
ID del recurso de cuenta que lo contiene

* ejemplo: {{.Account}}




| user_id | cadena | ruta | Verdadero  a| 
ID del recurso de usuario contenedor



| grupo_id | cadena | ruta | Verdadero  a| 
ID del recurso de grupo contenedor



| roleBinding_id | cadena | ruta | Verdadero  a| 
ID de la colección roleBinding que se va a listar

|===


== Cuerpo de la solicitud

Sustituye todo el recurso almacenado por el cuerpo de la solicitud JSON suministrado, conservando los valores clave que no son modificables por el usuario.

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 
Tipo de medio del recurso. Los valores definidos son:

* "application/astra-roleBinding"




| versión | cadena | Verdadero  a| 
Versión del recurso. Los valores definidos son:

* "1,0"
* "1,1"




| id | cadena | Falso  a| 
Identificador único global del recurso. Los valores definidos son:

* Cumple con el esquema UUIDv4




| userID | cadena | Falso  a| 
Cadena JSON que contiene un ID de recurso de usuario. Los valores definidos son:

* Cumple con el esquema de identificador de Astra. Si no se especifica en la creación, se utilizará un UUID nulo. En la creación solo se puede especificar userID o groupID.




| groupID | cadena | Falso  a| 
Cadena JSON que contiene un ID de recurso de grupo. Los valores definidos son:

* Cumple con el esquema de identificador de Astra. Si no se especifica en la creación, se utilizará un UUID nulo. En la creación solo se puede especificar userID o groupID.




| accountID | cadena | Falso  a| 
Cadena JSON que contiene el ID de un recurso de cuenta. Para crear, esto debe coincidir con el ID de cuenta en el URI de solicitud. Los valores definidos son:

* Cumple con el esquema del identificador Astra




| papel | cadena | Verdadero  a| 
Cadena JSON que contiene uno de los cuatro roles definidos. Los valores definidos son:

* "espectador"
* "miembro"
* "admin"
* "propietario"




| roleConstraints | array[string] | Falso  a| 
Matriz JSON de cadenas JSON que especifica el ámbito de la asignación de funciones. Los valores definidos son:

* Conforme a Astra Role Constraints Schema si no se especifica al crear, el valor se establecerá en una matriz de tamaño 1 que contenga la cadena "*", que representa "ámbito completo". Si no se especifica al actualizar, el valor se conservará sin modificación. Una matriz vacía representa "sin ámbito". Ejemplos:
* 
+
= Permitir el acceso a cualquier recurso: "roleConstraints": ["*"]

* 
+
= denegar el acceso a todos los recursos: "roleConstraints": []

* 
+
= Permitir el acceso únicamente a un recurso de espacio de nombres específico: "roleConstraints": [ "namespaces:id='6fa2f917-f730-41b8-9c15-17f531843b31'" ]

* 
+
= Permitir el acceso a un espacio de nombres específico y a todo lo que esté bajo él: "roleConstraints": [ "namespaces:id='6fa2f917-f730-41b8-9c15-17f531843b31'.*" ]

* 
+
= Permitir el acceso a todos los espacios de nombres etiquetados como "dev" en cualquier clúster en cualquier nube, y todo lo que está bajo ellos: "roleConstraints": [ "namespaces:kubernetesLabels='http://dev.example.com/appname=dev["dev.example.com/appname=dev'.*"]" ]

* 
+
= Permitir el acceso solo a todos los recursos de namespace: "roleConstraints": [ "namespaces:*" ]

* 
+
= Permitir el acceso a todos los recursos de espacios de nombres y a todo lo que esté bajo ellos: "roleConstraints": [ "namespaces:__.__" ]





| metadatos | link:#type_astra_metadata_update["type_astra_metadatos_update"] | Falso  a| 
Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


|===
.Ejemplo de solicitud
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-roleBinding",
  "version": "1.1",
  "role": "member",
  "roleConstraints": [
    "namespaces:id='c832e1dc-d7c3-464e-9c62-47bf91c46ce8'"
  ]
}
----
====


== Respuesta

[source]
----
Status: 204, Indicates if the roleBinding resource was updated.
----


== Respuesta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Respuesta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Respuesta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos del cuerpo de la solicitud no válidos

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Respuesta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Error

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| tipo | cadena | Verdadero  a| 



| título | cadena | Verdadero  a| 



| detalle | cadena | Verdadero  a| 



| estado | cadena | Verdadero  a| 



| correlationID | cadena | Falso  a| 

|===
.Ejemplo de respuesta de error
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definiciones

.Ver definiciones
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiqueta_tipo_astra

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 



| valor | cadena | Verdadero  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadatos_update

Metadatos especificados por el cliente y el servicio asociados con el recurso. Los valores definidos son:

* Conforme al esquema de metadatos de Astra. Si no se especifica al crear, se creará un objeto de metadatos sin etiquetas. Si no se especifica al actualizar, las etiquetas del objeto de metadatos, creationTimestamp y createdBy, se conservarán sin modificaciones.


[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| etiquetas | array[link:#type_astra_label["etiqueta_tipo_astra"]] | Falso  a| 



| CreationTimestamp | cadena | Falso  a| 



| Modificación.Marca de hora | cadena | Falso  a| 



| CreatedBy | cadena | Falso  a| 



| modifiedBy | cadena | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del parámetro de consulta no válido



| motivo | cadena | Verdadero  a| 
Razón por la que el parámetro de consulta no es válido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nombre | Tipo | Obligatorio | Descripción 


| nombre | cadena | Verdadero  a| 
Nombre del campo no válido del cuerpo de la solicitud



| motivo | cadena | Verdadero  a| 
Motivo por el que el campo del cuerpo de la solicitud no es válido

|===
====