---
sidebar: sidebar 
permalink: workflows/wf_clone_app_backup.html 
keywords:  
summary: Puede crear una nueva aplicación clonándola desde un backup. 
---
= Clonar una aplicación desde un backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede crear una nueva aplicación clonándola desde un backup.



== Antes de empezar

Tenga en cuenta lo siguiente acerca de este flujo de trabajo:

* Se utiliza una copia de seguridad de la aplicación
* La operación de clonado se ejecuta dentro del mismo clúster



NOTE: Para clonar una aplicación en un clúster diferente, debe actualizar el `clusterId` Parámetro en la entrada JSON según sea apropiado para su entorno.



== Paso 1: Seleccione la aplicación para clonar

Realice el flujo de trabajo link:wf_list_man_apps.html["Enumere las aplicaciones"] y seleccione la aplicación que desea clonar. Se necesitan varios valores de recursos para la llamada DE REST utilizada para clonar la aplicación.



== Paso 2: Seleccione la copia de seguridad a utilizar

Realice el flujo de trabajo link:wf_list_backups.html["Enumere los backups"] y seleccione la copia de seguridad que desea usar.



== Paso 3: Clonar la aplicación

Realice la siguiente llamada de API de REST.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /account/{account_id}/k8s/v2/qpps 
|===
.Parámetros de entrada adicionales
Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| JSON | Cuerpo | Sí | Proporciona los parámetros para la aplicación clonada. Vea el ejemplo siguiente. 
|===
.Ejemplo curl: Clone una aplicación desde un backup
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps" \
--include \
--header "Content-Type: application/astra-app+json" \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "type": "application/astra-app",
  "version": "2.0",
  "name": "mysql-clone3",
  "clusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "sourceClusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "namespace": "mysql",
  "backupID": "e24515bd-a28e-4b28-b832-f3c74dbf32fb"
}
----