---
sidebar: sidebar 
permalink: workflows/wf_create_snapshot.html 
keywords:  
summary: Es posible crear una instantánea para una aplicación específica. 
---
= Crear una instantánea para una aplicación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible crear una instantánea para una aplicación específica.



== Antes de empezar

Debe tener el ID de la aplicación para la que desea crear una instantánea. Si es necesario, puede usar el flujo de trabajo link:wf_list_man_apps.html["Enumere las aplicaciones"] para localizar la aplicación.



== Crear una copia de Snapshot

Realice la siguiente llamada de API de REST.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUBLICAR | /Account/{account_id}/k8s/v1/apps/{app_id}/appSnaps 
|===
.Parámetros de entrada adicionales
Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| id de aplicación | Ruta | Sí | Identifica la aplicación administrada donde se creará la instantánea. 


| JSON | Cuerpo | Sí | Proporciona los parámetros para la instantánea. Vea el ejemplo siguiente. 
|===
.Ejemplo de curl: Cree una instantánea para la aplicación
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v1/apps/$APP_ID/appSnaps" \
--include \
--header "Content-Type: application/astra-appSnap+jso" \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "type": "application/astra-appSnap",
  "version": "1.1",
  "name": "snapshot-david-1"
}
----