---
sidebar: sidebar 
permalink: workflows/wf_delete_backup.html 
keywords:  
summary: Es posible eliminar un backup asociado con una aplicación. 
---
= Eliminar una copia de seguridad
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible eliminar un backup asociado con una aplicación.



== Antes de empezar

Debe tener lo siguiente:

* ID de la aplicación a la que pertenece la copia de seguridad. Si es necesario, puede usar el flujo de trabajo link:wf_list_man_apps.html["Enumere las aplicaciones"] para localizar la aplicación.
* ID del backup que desea eliminar. Si es necesario, puede usar el flujo de trabajo link:wf_list_backups.html["Enumere los backups"] para localizar la snapshot.




== Elimine el backup

Realice la siguiente llamada de API de REST.


NOTE: Puede forzar la eliminación de una copia de seguridad fallida usando el encabezado de solicitud opcional como se describe a continuación.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| ELIMINAR | /Accounts/{account_id}/k8s/v1/apps/{app_id}/appbackups/{appBackup_id} 
|===
.Parámetros de entrada adicionales
Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| id de aplicación | Ruta | Sí | Identifica a la aplicación gestionada que posee el backup. 


| id de copia de seguridad | Ruta | Sí | Identifica el backup que se eliminará. 


| forzar eliminación | Encabezado | No | Se utiliza para forzar la eliminación de una copia de seguridad fallida. 
|===
.Ejemplo curl: Eliminar un único backup para la aplicación
[source, curl]
----
curl --request DELETE \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v1/apps/$APP_ID/appBackups/<BACKUP_ID>" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN"
----
.Ejemplo de curl: Elimine una copia de seguridad única para la aplicación con la opción force
[source, curl]
----
curl --request DELETE \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v1/apps/$APP_ID/appBackups/<BACKUP_ID>" \
--include \
--header "Force-Delete: true" \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN"
----