---
sidebar: sidebar 
permalink: workflows/wf_get_man_app.html 
keywords:  
summary: Puede recuperar todas las variables de recurso que describen una única aplicación. 
---
= Obtenga una aplicación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede recuperar todas las variables de recurso que describen una única aplicación.



== Antes de empezar

Debe tener el ID de la aplicación que desea recuperar. Si es necesario, puede usar el flujo de trabajo link:wf_list_man_apps.html["Enumere las aplicaciones"] para localizar la aplicación.



== Paso 1: Obtener la aplicación

Realice la siguiente llamada de API de REST.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| OBTENGA | /account/{account_id}/k8s/v2/apps/{app_id} 
|===
.Parámetros de entrada adicionales
Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| id de aplicación | Ruta | Sí | ID valor de la aplicación que se va a recuperar. 
|===
.Ejemplo de curl: Devuelve todos los datos de la aplicación
[source, curl]
----
curl --request GET \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps/$APP_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN"
----