---
sidebar: sidebar 
permalink: workflows/wf_list_snapshots.html 
keywords:  
summary: Puede enumerar las instantáneas que se han realizado para una aplicación específica. 
---
= Enumere las instantáneas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede enumerar las instantáneas que se han realizado para una aplicación específica.



=== Antes de empezar

Debe tener el ID de la aplicación para la que desea mostrar las instantáneas. Si es necesario, puede usar el flujo de trabajo link:wf_list_man_apps.html["Enumere las aplicaciones"] para localizar la aplicación.



=== 1. Enumere las instantáneas

Realice la siguiente llamada a la API de REST para enumerar las snapshots.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| OBTENGA | /Account/{account_id}/k8s/v1/apps/{app_id}/appSnaps 
|===


===== Parámetros de entrada adicionales

Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="15,10,10,65"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| id de aplicación | Ruta | Sí | Identifica la aplicación propietaria de las instantáneas mostradas. 


| cuente | Consulta | No | Si `count=true` el número de instantáneas se incluye en la sección de metadatos de la respuesta. 
|===


===== Ejemplo de curl: Devuelve todas las instantáneas de la aplicación

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appSnaps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Ejemplo curl: Devuelve todas las instantáneas de la aplicación y el recuento

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appSnaps?count=true' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Ejemplo de resultado JSON

[source, json]
----
{
    "items": [
        {
            "type": "application/astra-appSnap",
            "version": "1.1",
            "id": "1ce34da4-bb0a-4926-b925-4a5d85dda8c2",
            "hookState": "success",
            "metadata": {
                "createdBy": "a530e865-23e8-4e2e-8020-e92c419a3867",
                "creationTimestamp": "2022-10-30T22:44:20Z",
                "modificationTimestamp": "2022-10-30T22:44:20Z",
                "labels": []
            },
            "snapshotAppAsset": "0ebfe3f8-40ed-4bdc-88c4-2144fbda85a0",
            "snapshotCreationTimestamp": "2022-10-30T22:44:33Z",
            "name": "snapshot-david-1",
            "state": "completed",
            "stateUnready": []
        }
    ],
    "metadata": {}
}
----