---
sidebar: sidebar 
permalink: workflows/wf_restore_app_backup.html 
keywords:  
summary: Puede restaurar una aplicación creando una nueva aplicación a partir de una copia de seguridad. 
---
= Restaurar una aplicación desde una copia de seguridad
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede restaurar una aplicación creando una nueva aplicación a partir de una copia de seguridad.



== Paso 1: Seleccione la aplicación para restaurar

Realice el flujo de trabajo link:wf_list_man_apps.html["Enumere las aplicaciones"] y seleccione la aplicación que desea clonar. Se necesitan varios de los valores de los recursos para la llamada DE REST utilizada para restaurar la aplicación.



== Paso 2: Seleccione la copia de seguridad a utilizar

Realice el flujo de trabajo link:wf_list_backups.html["Enumere los backups"] y seleccione la copia de seguridad que desea usar.



== Paso 3: Restaurar la aplicación

Realice la siguiente llamada de API de REST. Debe proporcionar el ID para un backup (como se muestra a continuación) o una copia Snapshot.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| PUESTO | /account/{account_id}/k8s/v2/apps/{app_id} 
|===
.Parámetros de entrada adicionales
Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| JSON | Cuerpo | Sí | Proporciona los parámetros para la aplicación clonada. Vea el ejemplo siguiente. 
|===
.Ejemplo de curl: Restaure una aplicación in situ a partir de un backup
[source, curl]
----
curl --request PUT \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps/$APP_ID" \
--include \
--header "Content-Type: application/astra-app+json" \
--header "ForceUpdate: true" \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data @JSONinput
----
.Ejemplo de entrada JSON
[source, json]
----
{
  "type": "application/astra-app",
  "version": "2.0",
  "backupID": "e24515bd-a28e-4b28-b832-f3c74dbf32fb"
}
----