---
sidebar: sidebar 
permalink: workflows/wf_unmanage_app.html 
keywords:  
summary: Puede eliminar una aplicación gestionada cuando ya no sea necesaria. Al quitar una aplicación administrada también se eliminan las programaciones asociadas. 
---
= Desgestionar una aplicación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede eliminar una aplicación gestionada cuando ya no sea necesaria. Al quitar una aplicación administrada también se eliminan las programaciones asociadas.



== Antes de empezar

Debe tener el ID de la aplicación que desea anular la administración. Si es necesario, puede usar el flujo de trabajo link:wf_list_man_apps.html["Enumere las aplicaciones"] para localizar la aplicación.

Los backups y las instantáneas de la aplicación no se eliminan automáticamente cuando se eliminan. Si ya no necesita los backups ni las snapshots, debe eliminarlos antes de eliminar la aplicación.



== Anule la gestión de la aplicación

Realice la siguiente llamada a la API DE REST para eliminar la aplicación.

.Método HTTP y punto final
Esta llamada a la API de REST utiliza el siguiente método y extremo.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| ELIMINAR | /account/{account_id}/k8s/v2/apps/{app_id} 
|===
.Parámetros de entrada adicionales
Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| id de aplicación | Ruta | Sí | Identifica la aplicación que se va a eliminar. 
|===
.Ejemplo de curl: Eliminar una aplicación administrada
[source, curl]
----
curl --request DELETE \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps/$APP_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN"
----