---
sidebar: sidebar 
permalink: get-started/get_api_token.html 
keywords: token, obtain token 
summary: Necesita obtener un token de API Astra para utilizar la API REST de Astra Control. 
---
= Obtenga un token de API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Necesita obtener un token de API Astra para utilizar la API REST de Astra Control.



== Introducción

Un identificador de API identifica a la persona que llama a Astra y debe incluirse con cada llamada de API DE REST.

* Debe generar un token de API mediante la interfaz de usuario web de Astra.
* El procedimiento para generar un token es el mismo para ambos modelos de puesta en marcha de Astra. Solo la URL que se utiliza para acceder a Astra es diferente.
* La identidad de usuario que lleva el token y los permisos asociados son determinados por el usuario que creó el token.
* El token debe incluirse en el `Authorization` Encabezado de solicitud HTTP.
* Un token nunca caduca después de que se crea.
* Puede revocar un token en la interfaz de usuario web de Astra.


.Información relacionada
* link:../additional/revoke_token.html["Revocar un token de API"]




== Cree un token de API Astra

En los siguientes pasos se describe cómo crear un token de API de Astra.

.Antes de empezar
Necesita credenciales para una cuenta Astra.

.Acerca de esta tarea
Esta tarea genera un token de API en la interfaz web de Astra. También debe recuperar el ID de cuenta que también se necesita al realizar llamadas API.

.Pasos
. Inicia sesión en Astra con las credenciales de tu cuenta de la siguiente manera:
+
** Servicio Astra Control: link:https://astra.netapp.io["https://astra.netapp.io"^]
** Astra Control Center: Utilice la URL de su entorno local tal y como se establece durante la instalación


. Haga clic en el icono de figura situado en la parte superior derecha de la página y seleccione *acceso API*.
. Haga clic en *Generar token de API* en la página y luego haga clic en *Generar token de API* en la ventana emergente.
. Haga clic en el icono para copiar la cadena de token al portapapeles y guardarla en el editor.
. Copie y guarde el ID de cuenta que está disponible en la misma página.


.Después de terminar
Cuando accedes a la API de REST DE Astra Control mediante curl o un lenguaje de programación, debes incluir el token del portador de la API en HTTP `Authorization` solicite el encabezado.
