---
sidebar: sidebar 
permalink: get-started/online_api_ref.html 
keywords: reference, api reference 
summary: Puede acceder a los detalles de las llamadas API REST de Astra Control, incluidos los métodos HTTP, los parámetros de entrada y las respuestas. Esta referencia completa es útil cuando se desarrollan aplicaciones de automatización mediante la API DE REST. 
---
= Referencia de API en línea
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede acceder a los detalles de las llamadas API REST de Astra Control, incluidos los métodos HTTP, los parámetros de entrada y las respuestas. Esta referencia completa es útil cuando se desarrollan aplicaciones de automatización mediante la API DE REST.


NOTE: La documentación de referencia de la API DE REST se proporciona actualmente con Astra Control y está disponible en línea.

.Antes de empezar
Necesita una cuenta para Astra Control Center o Astra Control Service.

.Pasos
. Inicie sesión en Astra con sus credenciales de cuenta.
+
Acceda a las siguientes instalaciones para el servicio Astra Control: link:https://astra.netapp.io["https://astra.netapp.io"^]

. Haga clic en el icono de figura situado en la parte superior derecha de la página y seleccione *acceso API*.
. En la parte superior de la página, haga clic en la dirección URL que aparece en *Documentación de API*.
. Vuelva a introducir las credenciales de su cuenta si se le solicita.

